#!/usr/bin/env python3
"""Build the documentation-only PAY-HTML-001 review model. No app/data access."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
CURRENT='現行実装'; CONFIRMED='確定改修要件'; PROPOSED='提案'; UNDECIDED='未決'
PAY=['会計課給与班']; LOCAL=['局担当者']; BOTH=PAY+LOCAL; ADMIN=['業務マスタ管理者']; USER=['ログイン利用者']
S=[]
def source(id,path,title,section): S.append(dict(id=id,path=path,title=title,section=section))
source('SRC-STATUS','docs/handoff/STATUS.md','現在の作業と読取り対象','DOT-001最新状態と関連履歴の選択表示')
source('SRC-PAY','docs/requirements/payroll-confirmed-20261007.md','給与確定要件','PAYREQ-01～10、Q1～Q60、R1～R21、2026-10-08追補')
source('SRC-AD','docs/requirements/business-requirements.md','業務要件：採用前工程','A～D／AD-01～10')
source('SRC-E','docs/requirements/business-requirements.md','業務要件：給与登録','E／E-01～12')
source('SRC-F','docs/requirements/business-requirements.md','業務要件：通勤認定','F／F-01～08')
source('SRC-G','docs/requirements/business-requirements.md','業務要件：外部決定','G／G-01～06')
source('SRC-AUTH','docs/requirements/business-requirements.md','業務要件：役割・ルール','AUTH-01～04、PAY-01～05')
source('SRC-FR','docs/requirements/requirements.md','機能要件','FR-AD／FR-E／FR-F／FR-G／FR-PAY／FR-AUTH')
source('SRC-SCREEN','docs/requirements/screen-requirements.md','画面要件：現行・将来','1～6章、8～13章')
source('SRC-UIOCT','docs/requirements/screen-requirements.md','10月1日画面改修','SCR001～003 UI変更（CHANGE-20261001-SCR001-003-UI）')
source('SRC-JSCREEN','docs/requirements/screen-requirements.md','人給連携画面要件','2026-10-08／JLINK-UI-01～11')
source('SRC-I','docs/requirements/payroll-interface-decisions-20261008.md','人給の決定・保留','7. D1～D12、10. 残件、11. I1～I12')
source('SRC-IF','docs/design/detailed/payroll-jinkyu-interface.md','人給Excel・給与簿CSV仕様','2～6章、IF-01～12、PERIOD-01～05、11キー')
source('SRC-JDETAIL','docs/design/detailed/payroll-jinkyu-interface.md','承認画面の処理契約','7.1 出力／7.2 最新版照合／7.3 訂正・エラー・確定')
source('SRC-BASIC','docs/design/basic/basic-design.md','給与管理基本設計','現行画面境界、2026-10-07改修先、2026-10-08人給')
source('SRC-DATA','docs/design/basic/data-model.md','データ設計','現行隔離表、2026-10-07変更後論理モデル、2026-10-08連携')
source('SRC-DETAIL','docs/design/detailed/detailed-design.md','詳細設計：検索と試算','10.1～10.10、11.1～11.3、12章')
source('SRC-ATT','docs/design/detailed/detailed-design.md','詳細設計：勤怠','2026-09-29勤務時間報告／2026-10-01 UI／2026-10-07勤怠再取込')
source('SRC-CALC','docs/design/detailed/detailed-design.md','詳細設計：改修先','2026-10-07変更後処理契約、計算・人給照合・状態制御')
source('SRC-COMMUTE','docs/design/detailed/detailed-design.md','通勤HTMLの現行契約','10.4／CHANGE-20261003-COMMUTE-OFFICIAL／CHANGE-20261007-COMMUTE-CUTOVER')
source('SRC-OPEN','docs/requirements/open-decisions.md','未決・未照合','D-01～08、PD-01～09、2026-10-08モック・I決定反映後残件')
source('SRC-TEST','docs/testing/test-specification.md','人給連携試験仕様','IF-T01～12、JLINK-T01～08（業務試験未実施）')
source('SRC-DESIGN','docs/design/basic/design-system.md','B案デザイン基準','文字・色・余白・Fluent/DADS・Power Apps実機校正')
source('SRC-LEDGER-FIELDS','config/dataverse/payrollledger-columns.json','既存給与簿163項目定義','表示項目・現行型・必須性。新モデル物理設計とは別')
screens=[]
def screen(id,name,status,summary,tabs,roles,requirements,sources,notes):
    screens.append(dict(id=id,name=name,status=status,summary=summary,tabs=tabs,roles=roles,requirements=requirements,source_ids=sources,notes=notes))
screen('SCR-001','ログイン画面＆ホーム画面',CURRENT,'現行4主ボタンから業務画面へ移動。外部Microsoft認証をCanvas内画面とみなさない。',[],USER,['COMMON-SCREEN-001','COMMON-NAV-001','SCR001-UI-001'],['SRC-UIOCT','SRC-DETAIL','SRC-STATUS'],['10月1日以降はホームからSCR-005へ直接移動しない。SCR-002経由。','現行のPoCデータ一括取込は将来のE専用取込画面と別物。','確認用の所属・管理者切替は表示検証用。業務認可を変更しない。','人給連携・データ一括取込みの追加入口は確定改修要件。'])
screen('SCR-002','職員マスタ検索・詳細',CURRENT,'検索・履歴・6タブ表示の現行画面。E・F・Gの将来業務を既存タブに追加する。',['基本情報','勤務条件','通勤','社会保険','税固定控除','給与簿'],BOTH,['SCR002-LT-003','SCR002-EDIT-001','SCR002-E-001','SCR002-F-001','SCR002-G-001','SCR002-G-002'],['SRC-SCREEN','SRC-DETAIL','SRC-PAY'],['住民税は税固定控除タブ内。外部手続きタブを新設しない。','給与簿は常時読取り専用。既存56項目の読取検証は新モデルの編集・保存合格を意味しない。','給与簿163項目表示と人給出力237列は別契約。','勤務条件・保険等の確認状態は改修先。現行実装へ読み替えない。'])
screen('SCR-003','勤務時間報告画面',CURRENT,'所属×勤務月の報告。現行は一覧内編集・全置換取込。確定改修要件は追加更新方式。',[],BOTH,['PAYREQ-06','COMMON-SCREEN-001'],['SRC-ATT','SRC-UIOCT','SRC-PAY'],['初期読取り専用。現行は入力中の報告を編集し、成功後に再取得。','報告済みロックと差戻しを維持。実効業務認可、同時操作・途中障害は別検証。','現行全置換と将来の未掲載行保持を同時に実装済みとしない。'])
screen('SCR-004','期末勤勉支給率登録画面',CURRENT,'現行6画面の一つ。職員×支給対象期間の期末・勤勉別率は確定改修要件。',[],PAY,['COMMON-SCREEN-001','PAYREQ-07'],['SRC-SCREEN','SRC-PAY','SRC-OPEN'],['内部の正式項目、保存部品、率の入力範囲、基礎額・式・端数は未入力。','画面の存在を別率登録の実装・受入完了としない。'])
screen('SCR-005','支給明細画面',CURRENT,'選択職員・対象月の内蔵仮例による支給内訳試算。給与班の本番計算・確定と分ける。',[],BOTH,['SCR005-ACT-001','SCR005-ACT-004','SCR005-UI-004','SCR005-UI-015','COMMON-NAV-003'],['SRC-SCREEN','SRC-DETAIL','SRC-OPEN'],['現行再計算ではDataverseの保存・支給確定・支払処理を行わない。','通常PCサマリー固定と狭い・低い領域の全体スクロールは承認A。引継ぎ公開38で通常到達を観測。focus見切れ・履歴AX差、正式P/H・最終照合は残る。制度式・Issue #51は未完了。','改修先計算の配置をこの画面へ断定しない。レビュー上の候補配置には提案を明記。'])
screen('SCR-006','メンテナンス画面',CURRENT,'現行管理者限定画面と対象月設定。業務マスタ管理を改修先として整理。',[],ADMIN+['現行管理者'],['COMMON-AUTH-002','SCR006-RULE-001','PAYREQ-09'],['SRC-SCREEN','SRC-ATT','SRC-PAY'],['業務マスタ管理者とシステム管理権限は別。給与班との兼務可能。','現行の管理者切替UIは実効認可ではない。'])
screen('FUT-IMPORT','データ一括取込み',CONFIRMED,'Eの異動情報Excelを複数職員分取り込み、行別不備・重複候補を確認する専用画面。',[],PAY,['FUT-IMPORT-001','FR-E-01'],['SRC-E','SRC-SCREEN'],['仮ID。正式画面ID・Excel列・再取込方法は未決。','正常行を先に反映し、問題行は給与班が判断する。勤怠取込の全件検証契約と区別。','A～Dは前工程の受渡条件のみを図示し、異動情報アプリそのものを作らない。'])
screen('FUT-JLINK','人給連携',CONFIRMED,'支給回ごとに出力・給与簿取込・最新照合・給与班確定を行う承認済み構成。',['支給回の状況','出力','取込・照合'],PAY,['JLINK-UI-01','JLINK-UI-02','JLINK-UI-11','PAYREQ-08'],['SRC-JSCREEN','SRC-I','SRC-JDETAIL'],['仮ID。正式画面ID・物理実装未入力。モック承認を実装合格と扱わない。','I1～I3はモック承認根拠。架空の人数・金額・日付は仕様に採用しない。','計算版選択、人給取込成否の手入力、確定確認ダイアログは設けない。','出力前確認は行う。D9～D12等の式精査は保留。'])
screen('SCR-007','遡及差額の確認（仮）',CONFIRMED,'先行して独立画面で差額結果の確認・確定を扱う。返納操作配置は提案。',[],PAY,['SCR007-DIFF-001','FUT-STATE-PAY','PAYREQ-08'],['SRC-SCREEN','SRC-AUTH','SRC-PAY','SRC-OPEN'],['仮ID。完成後のSCR-002タブ統合の要否はD-08。入口・返納操作の詳細配置は未決。','確認待ち→確定の2状態。支給・回収実績は別記録。','支払済み結果を変更しない。'])
screen('EXT-JINKYU','人給システム（外部）',CONFIRMED,'職員がExcelを取り込み、人給で必要な処理を行い給与簿CSVを出力する外部境界。',[],PAY,['IF-01','IF-09','IF-10','I10'],['SRC-IF','SRC-JDETAIL'],['非常勤給与アプリ内の新画面ではない。','人給への直接接続・自動操作・エラー自動取得は確定していない。'])
screen('EXT-COMMUTE','通勤認定簿HTML（別タブ）',CURRENT,'認定GUIDで再取得する公式様式。ブラウザー印刷からA4横2ページの1PDFを保存。',[],BOTH,['SCR002-COM-003','FR-F-04'],['SRC-COMMUTE','SRC-STATUS'],['10月7日の通常入口切替と旧リソース撤去後に受入PASS。新データモデルとの帳票連携は別の未実装契約。','現行は71表示欄の様式v1.02。旧84データ列との数の違いを同一視しない。','権限実効性・全データ組合せ・総合試験は既存の受入PASSから推定しない。'])
ops=[]
def op(id,screen_id,title,business_id,status=CONFIRMED,req=None,src=None,dest=None,tab='該当なし',mode='読取り',dtab=None,dmode=None,roles=None,**kw):
    d=dict(id=id,transition_id=id.replace('OP-','TR-',1),screen_id=screen_id,destination_screen_id=dest or screen_id,title=title,business_id=business_id,status=status,requirements=req or [],source_ids=src or ['SRC-PAY'],origin_tab=tab,origin_mode=mode,destination_tab=dtab or tab,destination_mode=dmode or mode,control=('提案：'+title if status!=CURRENT else title),method='クリック／キーボード実行（具体部品は未入力）',roles=roles or BOTH,row_scope='給与班は全対象、局担当は自局記録と必要な共通基本情報。実効方式はPD-04。',visible='対象画面・タブ内。権限別の具体表示条件は未入力。',enabled='対象・権限・業務状態を検証した場合。物理方式は未入力。',preconditions='認証済みで対象レコードを識別できること。',validation='対象職員・対象履歴・操作権限の整合を確認。詳細検証値は未入力。',process='操作の業務条件に従う。具体的処理方式は未入力。',reads=['対象の論理レコード（正式物理名未入力）'],writes=[],retained='ログイン主体、選択対象、参照元の識別情報。',reset='明記のないリセット範囲は未決。',success='目的の状態と再表示を確認する。実装合格を意味しない。',failure='エラーを示し成功扱いしない。復旧・再実行の詳細は未決。',cancel='処理開始前の取消は状態を変更しない（画面操作案）。',unsaved='未保存入力の扱いは個別契約を優先。未定義の画面は未決。',acceptance=['対象・権限・業務状態と出力／保存結果が対応する。'],notes=[])
    if status==CURRENT:
        d['row_scope']='現行要件は同一所属制限。業務認可の実装・全経路検証は未完了。改修先の給与班全局／局担当自局と区別する。'
    elif d['roles']==PAY:
        d['row_scope']='給与班が担当業務について全対象職員を扱う。局担当者・本人にはこの操作を許可しない。実効方式はPD-04。'
        d['enabled']='給与班の実効権限、対象、業務状態を検証した場合。物理方式はPD-04。'
    elif d['roles']==LOCAL:
        d['row_scope']='局担当者の自局に属する業務記録。必要な共通職員基本情報だけを併用し、他局履歴を開示しない。実効方式はPD-04。'
    elif d['roles']==ADMIN:
        d['row_scope']='業務マスタ管理者の業務マスタ範囲。給与班との兼務は可能だが給与班またはシステム管理者だけでは許可しない。'
        d['enabled']='業務マスタ管理ロールを持ち、対象・有効期間・入力条件を検証した場合。'
    d.update(kw); ops.append(d)
# Current home routes. The removed direct SCR-001→005 route is intentionally absent.
for suffix,dest,title in [('STAFF','SCR-002','職員マスタ検索'),('ATTENDANCE','SCR-003','勤務時間報告'),('RATES','SCR-004','期末勤勉支給率登録'),('MAINTENANCE','SCR-006','メンテナンス')]:
    op('OP-001-'+suffix,'SCR-001',title,'共通ナビゲーション',CURRENT,['COMMON-NAV-001','COMMON-CONTEXT-001'],['SRC-UIOCT','SRC-DETAIL'],dest=dest,roles=USER,process='最新の4主ボタンから対象画面へ移動する。',reads=['ログイン主体','現行表示確認用コンテキスト'],enabled='メンテナンスは現行管理者のみ。他3入口はログイン済み。',row_scope='現行所属制限。将来の給与班全局・局担当自局の認可は別契約。',success='移動先の画面IDと主体を確認。',notes=['UI選択だけで実効権限を得たとみなさない。','ホームからSCR-005への直通は10月1日削除済み。'])
op('OP-001-IMPORT','SCR-001','データ一括取込み','E',req=['FUT-IMPORT-001','FR-E-01'],src=['SRC-E','SRC-SCREEN'],dest='FUT-IMPORT',roles=PAY,control='データ一括取込み',process='E専用の行別取込画面を開く。',notes=['現行PoCボタンをE本機能と読み替えない。'])
op('OP-001-JLINK','SCR-001','人給連携','人給連携',req=['JLINK-UI-01','I3'],src=['SRC-JSCREEN','SRC-I'],dest='FUT-JLINK',dtab='支給回の状況',roles=PAY,control='人給連携',process='同一画面3タブの人給連携へ移動する。')
# Search and edit contracts.
op('OP-002-SEARCH','SCR-002','職員を検索','職員検索',CURRENT,['SCR002-UI-004','SCR002-LT-007'],['SRC-DETAIL','SRC-OPEN'],control='検索',process='入力条件を確定し、認可範囲の職員を取得する。',reads=['職員基本','所属・在籍状態'],reset='正常0件時は選択職員・詳細・履歴・認定GUID・給与を全て空にする。',failure='通信失敗・権限拒否と正常0件を区別し、旧職員を表示しない。',acceptance=['12桁文字列・先頭ゼロを保持。','0件で旧詳細や帳票が残らない。'],notes=['現行検索の利用者別結果と未照合はopen-decisionsを参照。全条件PASSではない。'])
op('OP-002-SELECT','SCR-002','職員を選択','職員検索',CURRENT,['SCR002-LT-002','SCR002-EDIT-003'],['SRC-DETAIL'],control='検索結果の職員行',process='12桁番号と所属を再検証し、当該職員の必要データを取得する。',reads=['職員基本','勤務条件・通勤・保険・税・給与簿の履歴'],reset='職員切替後に旧職員の履歴・通勤GUID・給与表示を消去。',retained='検索入力・結果・ページ位置。',unsaved='未保存なら先に破棄確認。キャンセル時は現在の職員と入力を保持。',notes=['選択だけでサイドバーを自動的に閉じない。'])
op('OP-002-SIDEBAR','SCR-002','検索欄を開閉','職員検索',CURRENT,['SCR002-LT-002'],['SRC-DETAIL'],control='検索サイドバー開閉',process='検索欄の幅と表示を切替え、閉じた領域をTab対象から外す。',reads=['画面表示状態'],retained='検索入力・検索結果・選択職員・ページ位置・入力バッファ。',reset='なし。開閉で再検索・初期化しない。',unsaved='保持する。')
op('OP-002-TABS','SCR-002','詳細タブを切替','職員詳細',CURRENT,['SCR002-LT-003','SCR002-EDIT-003'],['SRC-DETAIL','SRC-SCREEN'],tab='基本情報／勤務条件／通勤／社会保険／税固定控除／給与簿',control='6タブ',process='取得済みデータでタブを切替える。給与簿は常時読取り専用。',reads=['取得済み詳細・履歴'],retained='職員・区分ごとの履歴選択・未保存入力。',reset='なし。タブ切替だけで再取得しない。',unsaved='編集入力を保持。')
op('OP-002-HISTORY','SCR-002','履歴を選択','職員詳細',CURRENT,['SCR002-LT-004'],['SRC-DETAIL','SRC-DATA'],tab='勤務条件／通勤／社会保険／税固定控除',control='履歴一覧',process='選択GUIDで該当職員の履歴を表示する。0件・単一件・複数件を区別する。',reads=['対象タブの履歴'],validation='GUID・親職員Lookup・12桁職員番号の一致。',unsaved='履歴切替で同一入力を失う場合の扱いは詳細未決。提案：未保存確認。',notes=['同一職員の複数履歴を無条件Firstで潰さない。'])
op('OP-002-EDIT','SCR-002','編集モードへ','職員詳細',CURRENT,['SCR002-EDIT-001'],['SRC-DETAIL','SRC-SCREEN'],tab='基本情報／勤務条件／通勤／社会保険／税固定控除',dmode='編集',control='編集モード',enabled='編集権限と保存先が確定した対象列。給与簿は非対象。',process='対象レコードと表示値を確認し、許可列の入力バッファを作る。',reads=['選択職員・選択履歴','許可列'],writes=['画面内の編集バッファ'],notes=['現行モード切替の存在を各履歴の実保存合格としない。'])
op('OP-002-SAVE','SCR-002','変更を保存','職員詳細',req=['SCR002-EDIT-002','SCR002-EDIT-003'],src=['SRC-DETAIL','SRC-OPEN'],tab='基本情報／勤務条件／通勤／社会保険／税固定控除',mode='編集',dmode='読取り',control='保存',validation='保存直前に対象職員・履歴ID・所属権限・許可列を再検証。',process='変更された許可列のみ保存し、再取得した内容と一致を確認して読取りへ戻す。',reads=['選択レコード','編集差分'],writes=['保存先確認済みの職員基本・履歴レコード'],reset='保存と再取得一致後に当該編集バッファを消去。',success='再取得成功後に取得日時を更新。',failure='入力と選択を保持。保存後の再取得失敗を確認済みとしない。部分更新を全件成功にしない。',unsaved='保存失敗時は保持。',notes=['各列の正式保存先・実効権限はD-02／PD-01・04残件。給与簿は書込禁止。'])
op('OP-002-READMODE','SCR-002','読取りモードへ','職員詳細',CURRENT,['SCR002-EDIT-003','SCR002-EDIT-004'],['SRC-DETAIL'],mode='編集',dmode='読取り',control='読取りモード',process='変更なしなら読取りへ。未保存なら破棄確認を表示する。',reads=['編集バッファの変更状態'],unsaved='「変更を破棄して移動しますか」。常設の変更を破棄ボタンは設けない。')
op('OP-002-CANCEL','SCR-002','破棄確認を取消','共通取消',CURRENT,['SCR002-EDIT-003'],['SRC-DETAIL'],mode='破棄確認',dmode='編集',control='確認内のキャンセル',process='保留した移動・職員変更・読取り切替を取消し、編集を続ける。',reads=['保留中の遷移','編集バッファ'],retained='現在職員・タブ・履歴・全未保存入力。',reset='保留中の遷移要求だけを解除。',unsaved='全て保持。')
op('OP-002-DISCARD','SCR-002','破棄して続行','共通取消',CURRENT,['SCR002-EDIT-003'],['SRC-DETAIL'],mode='破棄確認',dmode='保留中の遷移先状態',control='確認内の続行',process='明示的な続行を受けた後に入力を破棄し、保留していた目的画面／職員へ移動する。',reads=['保留中の遷移','編集バッファ'],reset='承認された未保存入力。',unsaved='続行選択後にだけ破棄。',notes=['destination_screen_idは確認の表示元。実際の遷移先は保留中の操作が持つ。'])
op('OP-002-LEDGER','SCR-002','給与簿の月範囲変更','給与簿参照',CURRENT,['SCR002-PAY-005','SCR002-PAY-006','SCR002-PAY-008'],['SRC-DETAIL'],tab='給与簿',control='表示開始月／表示終了月と隣接カレンダー',validation='開始月≦終了月。解釈不能支給日は例外として表示。',process='職員と月範囲で取得し、163項目×登録済み支給行を表示。同月複数行は別列。',reads=['基準給与簿の163項目','支給年月日・番号・行GUID'],reset='範囲外の表示列を再構成。未登録月の空列は作らない。',acceptance=['0・負数・NULLを区別する。','末尾まで到達し、月列と項目が対応する。'],notes=['改修後は人給CSV取込給与簿を読取り専用で表示する。'])
op('OP-002-PAYDETAIL','SCR-002','支給明細へ','支給明細参照',CURRENT,['COMMON-NAV-003','COMMON-CONTEXT-002'],['SRC-UIOCT','SRC-DETAIL'],dest='SCR-005',control='支給明細画面',process='選択職員・対象月を渡し、遷移先で存在と所属を再確認。',reads=['選択職員','対象月'],retained='職員番号・対象月・ログイン主体。検索結果保持は現行未達記録あり。',unsaved='未保存ならSCR-002の破棄確認を先行。',notes=['ホーム直通を復活させない。'])
# Home returns are explicit per screen, without creating any extra forward route.
for sid in ['002','003','004','005','006']:
    op('OP-'+sid+'-HOME','SCR-'+sid,'ホームへ戻る','共通ナビゲーション',CURRENT,['COMMON-NAV-002','COMMON-CONTEXT-001'],['SRC-DETAIL','SRC-UIOCT','SRC-ATT'],dest='SCR-001',control='ホーム',roles=USER,process='ログイン主体を保持してホームへ戻る。',reads=['画面コンテキスト'],retained='ログイン者の氏名・メール。',enabled='SCR-003は編集中にホームを無効化。他画面は対象条件に従う。',unsaved='SCR-002は破棄確認。SCR-003は編集中の遷移を無効化し読取り切替の確認へ。SCR-004／006は未決。SCR-005は試算のみ。')
# Attendance: current and confirmed future intentionally separate.
op('OP-003-SELECT','SCR-003','局・月・報告を選択','勤怠',CURRENT,['PAYREQ-06'],['SRC-ATT'],control='報告一覧／対象月／課室絞込み',process='有効対象月と報告を選び、有効バッチ明細をNo順・課室で表示する。',reads=['T_勤務時間報告','T_勤務時間報告明細','M_勤務報告対象月'],retained='編集ドラフトは課室フィルター外も含む全明細を保持。',reset='報告切替時は旧選択ヘッダー・バッチ・明細を消去。',enabled='編集中は報告変更不可。',notes=['現行の局名手入力・表示確認用権限UIは業務認可未実装。'])
op('OP-003-EDIT','SCR-003','勤務実績を一覧編集','勤怠',CURRENT,['PAYREQ-06'],['SRC-UIOCT','SRC-ATT'],mode='入力中・読取り',dmode='入力中・編集',control='編集モード',enabled='入力中の報告のみ。報告済み・取込中は不可。',process='同画面内に全明細のドラフトを作り日数・時間・備考を編集する。',reads=['選択報告の全明細'],writes=['画面内ドラフト'],validation='超勤は小数3桁、欠勤は整数時間。',notes=['旧明細クリック別編集画面は廃止。'])
op('OP-003-SAVE','SCR-003','勤務実績を保存','勤怠',CURRENT,['PAYREQ-06'],['SRC-ATT','SRC-UIOCT'],mode='入力中・編集',dmode='入力中・読取り',control='保存',process='全明細・reportId・expectedVersionを既存保存フローへ送り、成功後にヘッダー・有効明細を再取得。',reads=['ドラフト全件','報告状態・版'],writes=['現行報告の新有効バッチ・版'],validation='数値変換、整数／小数精度、報告入力中、期待版。',failure='入力変換・フロー失敗時は通知してドラフトと編集を保持。',reset='成功後にドラフトを消去。',unsaved='失敗時保持。')
op('OP-003-READMODE','SCR-003','勤怠編集を取り消す','勤怠',CURRENT,['PAYREQ-06'],['SRC-UIOCT','SRC-ATT'],mode='入力中・編集',dmode='入力中・読取り',control='読取りモード',process='未保存変更があれば破棄確認。続行で破棄、取消で全ドラフトを保持。',reads=['Dirty状態','編集ドラフト'],unsaved='読み取り切替の破棄確認を使う。編集中のホーム・取込・報告・報告選択は無効。',cancel='編集・入力を保持する。')
op('OP-003-IMPORT-CURRENT','SCR-003','現行Excel全置換取込','勤怠（現行）',CURRENT,['PAYREQ-06'],['SRC-ATT'],control='Excel取込',mode='入力中・読取り',process='現行は新GUIDバッチへ全行保存し、件数・版・入力中状態確認後に有効バッチを全置換する。',reads=['1ファイル.xlsxのTestData','対象報告・現在版'],writes=['現行勤務時間報告の新バッチ・有効版'],validation='10MB以内、20列、1～999件、数字職員番号、No重複、数値範囲・精度。',enabled='報告入力中、未編集中。',notes=['これは現行契約。10月7日確定の追加更新方式は次の操作で分離。','999件境界・同時操作・途中障害の実測合格は未確認。'])
op('OP-003-IMPORT','SCR-003','勤務実績を追加更新取込','勤怠（改修先）',req=['PAYREQ-06'],src=['SRC-PAY','SRC-ATT','SRC-OPEN'],mode='入力中',dmode='検証・反映中',roles=BOTH,enabled='入力中のみ。報告済み不可。取込中は同報告の編集・提出停止。',validation='全件を先に検証。12桁番号、超勤小数3桁、欠勤整数、重複・必須値。一般必須空欄と行キーは未入力。',process='掲載行を追加／更新。手修正済みでもファイル優先。空欄は消去し0は0。非掲載の既存職員行を残す。',reads=['取込ファイル全件','対象報告の既存行'],writes=['対象報告の掲載職員行','取込処理状態'],failure='反映途中の不完全結果を計算から除外し、復旧・再実行情報を残す。自動ロールバック保証なし。',acceptance=['掲載行は上書き・空欄消去・0保持。非掲載行は保持。','取込中は編集と報告を拒否。','失敗途中の結果を計算へ渡さない。'],notes=['全件検証後反映。Eの正常行先行取込とは異なる。','PD-05で排他・冪等・版切替・復旧を決める。'])
op('OP-003-RECOVER','SCR-003','取込失敗を復旧・再実行','勤怠',req=['PAYREQ-06','PAYREQ-10'],src=['SRC-ATT','SRC-OPEN'],mode='不完全・計算除外',dmode='入力中',process='失敗情報と対象報告を確認し、不完全結果を利用せず復旧・再実行する。',reads=['取込処理状態','検証結果','既存報告版'],writes=['復旧後の取込処理状態・利用可能版（方式未決）'],failure='不完全の隔離を維持。未確認の復旧成功を表示しない。',notes=['復旧UI、再実行範囲、ロールバック・冪等方式は未決。操作名は提案。'])
op('OP-003-ROWEDIT','SCR-003','職員行を追加・削除','勤怠',req=['PAYREQ-06'],src=['SRC-PAY','SRC-OPEN'],mode='入力中・編集',dmode='入力中・編集',process='対象報告内で職員行を追加／削除できるようにする。保存時の所属・対象職員・状態を検証する。',reads=['職員基本','入力中の報告'],writes=['対象報告の職員行'],validation='職員識別・重複・数値精度。削除時の具体的確認と復旧方式は未入力。',notes=['行追加／削除は確定改修要件。現在実装済みとしない。'])
op('OP-003-REPORT','SCR-003','勤務時間を報告','勤怠',CURRENT,['PAYREQ-06'],['SRC-ATT','SRC-PAY'],mode='入力中・読取り',dmode='報告済み',control='報告',enabled='未編集中、取込中でなく、保存済み報告を対象とする。',process='現行は確認モーダルから実行。報告後は編集・取込を停止する。',reads=['対象報告・状態・版'],writes=['報告状態'],acceptance=['報告済みでは編集・取込できない。'],notes=['給与班・自局の実効ロール検証は改修先契約。'])
op('OP-003-RETURN','SCR-003','報告を差し戻す','勤怠',req=['PAYREQ-06','PAYREQ-07'],src=['SRC-ATT','SRC-PAY'],mode='報告済み',dmode='入力中',roles=PAY,control='提案：差戻し（現行は戻し）',process='給与班が差戻し後、局担当が訂正・再提出。影響する未払い結果は再計算・再照合。',reads=['対象報告・影響支給回'],writes=['報告状態','再処理の対象情報'],notes=['現行に戻し操作あり。給与班限定の実効認可を実装済みとしない。'])
# Rates, current test payroll, maintenance.
op('OP-004-RATES','SCR-004','期末・勤勉率を登録','期末勤勉',req=['PAYREQ-07'],src=['SRC-PAY','SRC-SCREEN','SRC-OPEN'],roles=PAY,mode='対象選択・編集',dmode='保存後',process='職員×支給対象期間に期末と勤勉の支給率を別々に登録する。',reads=['職員','支給対象期間'],writes=['期末率・勤勉率'],validation='具体的な率範囲・初期値・丸め・必要条件は未入力。',notes=['単一率に統合しない。給与班という操作担当の配置はレビュー提案。','賞与の基礎額・式・適用判定は未決。'])
op('OP-005-MONTH','SCR-005','試算対象月を変更','現行試算',CONFIRMED,['SCR005-ACT-003','SCR005-ACT-005','SCR005-ACT-006'],['SRC-DETAIL','SRC-OPEN'],control='支給対象月',process='対象変更で旧結果と根拠を失効させ、新入力を確認する。未選択なら選択案内。',reads=['選択職員・対象月の内蔵仮例'],reset='旧金額・算定根拠・計算状態。',success='未登録は「—」と理由。登録済み検証済み0円は0円。',notes=['旧根拠文残留の現行実装差分は未解消として示す。'])
op('OP-005-RECALC','SCR-005','内蔵仮例を再計算','現行試算',CURRENT,['SCR005-ACT-004','SCR005-CALC-008'],['SRC-DETAIL','SRC-OPEN'],control='再計算',process='入力版を固定して仮例の検証・試算を実行する。Dataverse保存・確定・支払を呼ばない。',reads=['内蔵仮例の勤務・単価・認定通勤・控除'],writes=['画面内試算結果'],enabled='職員・対象月が有効。計算中の連打抑止。',failure='不足・重複・取得失敗を区別して「—」。',notes=['本番制度式・端数仕様へ転用しない。Issue #51未完了。'])
op('OP-005-DETAILS','SCR-005','支給・控除内訳を開閉','現行試算',CONFIRMED,['SCR005-ACT-007','SCR005-UI-015'],['SRC-DETAIL'],control='支給の内訳／控除の内訳',process='支給・控除を個別に開閉し、見出し金額と固定サマリーを維持する。',reads=['画面内試算結果'],reset='閉じた領域の空白・Tab対象を除去。',notes=['現行の固定サマリー実装差分を合格にしない。'])
op('OP-005-RETURN','SCR-005','職員詳細へ戻る','支給明細参照',CURRENT,['COMMON-NAV-003','SCR005-ACT-002'],['SRC-DETAIL'],dest='SCR-002',control='職員マスタ検索',process='職員番号・対象月を戻し、存在・所属を再確認する。',reads=['選択職員・対象月'],retained='職員番号・対象月。',notes=['検索結果の完全保持には現行差分記録あり。'])
op('OP-006-MONTH','SCR-006','勤務報告対象月を設定','対象月管理',CURRENT,['PAYREQ-06'],['SRC-ATT'],roles=['現行管理者'],control='対象月の有効化／解除',process='勤務時間報告に選択できる対象月の有効状態を保存する。',reads=['M_勤務報告対象月'],writes=['勤務報告対象月の有効状態'],notes=['表示用管理者UIを業務認可としない。既存報告への影響詳細は未入力。'])
op('OP-006-RULE','SCR-006','業務マスタを登録・改定','給与ルール',req=['SCR006-RULE-001','PAY-01','PAY-02','PAYREQ-09'],src=['SRC-AUTH','SRC-PAY','SRC-SCREEN'],roles=ADMIN,mode='編集',dmode='保存後',process='単価・区分・組織・予算・控除項目等を登録し、改定には適用開始日と対象を管理。旧ルール・額を保持する。',reads=['業務マスタ・適用履歴'],writes=['業務マスタの新規／改定情報'],validation='正式項目・入力範囲・承認公開手順は未決。組織は階層なし。',notes=['給与班と兼務可能。システム管理権限だけで業務変更を許可しない。'])
op('OP-006-END','SCR-006','マスタを使用停止','給与ルール',req=['PAYREQ-09'],src=['SRC-PAY','SRC-OPEN'],roles=ADMIN,process='使用停止または終了で履歴を残す。物理削除はこの操作に含めない。',reads=['対象マスタ・参照履歴'],writes=['使用停止／終了情報'],validation='誤登録の物理削除条件は未入力。',notes=['復帰操作や影響期間の詳細は未決。'])
# A-D: intake boundary, not a second personnel application.
op('OP-AD-CANDIDATE','FUT-IMPORT','発令情報から候補作成','A～D',req=['AD-01','AD-02','AD-03','AD-09','FR-AD-01','FR-AD-04'],src=['SRC-AD','SRC-FR','SRC-OPEN'],dest='SCR-002',dtab='勤務条件',dmode='確認待ち',roles=PAY,control='前工程通知の受領（自動連携方式未決）',method='Cの発令情報登録完了時。自動作成は目標。',preconditions='通常職員はA初任給確定・B採用起案決裁後。調査員はCから開始。',process='C完了を起点に確認待ち候補を作る。調査員は採用日で給与ルール版を選ぶ。',reads=['異動情報アプリの発令情報','調査員用ルール・適用日'],writes=['給与情報の確認待ち候補'],validation='決裁完了だけでは候補を作らない。職員番号発行前も候補作成・確認可能。',notes=['自動通知・作成の方式と実現可否は未決。採用前候補と一人一行職員基本の接続はPD-08。'])
op('OP-AD-NUMBER','SCR-002','発行職員番号を反映','D',req=['AD-04','AD-05','FR-AD-02','PAYREQ-01','PAYREQ-02'],src=['SRC-AD','SRC-PAY','SRC-OPEN'],tab='基本情報',control='発行情報の自動反映（目標）',method='Dの番号発行後の受渡し。具体方式未決。',process='採用ごとの識別子で同じ候補へ12桁番号を反映する。再採用は新しい採用識別子を使う。',reads=['採用ごとの識別子','発行職員番号'],writes=['既存候補と職員基本の対応（物理方式未決）'],validation='番号一意・先頭ゼロ・GUID Lookup整合。職員基本を再採用のたびに重複作成しない。',notes=['手動紐づけ操作を設けない。番号発行を候補作成・確認確定の前提にしない。'])
op('OP-AD-CHANGE','SCR-002','前工程変更の差異確認','A～D変更',req=['AD-08','E-09','FR-E-03'],src=['SRC-AD','SRC-E'],tab='勤務条件',dmode='確認待ち',roles=PAY,process='変更前を保持。給与班の修正値と前工程変更値が食い違えば自動上書きせず採用値を給与班が判断する。',reads=['変更前候補','前工程変更値','給与班修正値'],writes=['採用された変更・変更前後履歴','確認待ち状態'],validation='確定後変更なら再確認・再確定まで計算に使用しない。',notes=['自動受領方式は未決。差異の採用値判断はEの前工程変更でありG外部決定の採否判定ではない。'])
op('OP-AD-CANCEL','SCR-002','採用取消を反映','A～D取消',req=['AD-06','AD-07','FR-AD-03'],src=['SRC-AD'],mode='確認待ち／確定',dmode='採用取消',roles=PAY,control='取消情報受領（連携方式未決）',method='秘書課が前工程で登録した取消情報を受領したとき。自動連携方式は未決。アプリ内の手動取消ボタンを確定しない。',visible='採用取消の状態を既存候補・履歴で参照する。具体表示は未入力。',enabled='前工程の取消情報と同じ候補との対応を確認できること。給与班のボタンクリックで取消を創作しない。',preconditions='給与支給前。秘書課が異動情報アプリへ取消を登録。',process='確認待ち・確定のいずれからも採用取消へ移し、候補を保持して給与計算から除外。',reads=['取消情報・対応候補'],writes=['採用取消状態・履歴'],retained='取消前候補・変更履歴。',notes=['削除しない。採用取消に伴う既支給返納は対象外。'])
# E import and source maintenance.
op('OP-IMPORT-VALIDATE','FUT-IMPORT','Excelの行を検証','E',req=['E-02','E-03','E-04','E-05','FR-E-01'],src=['SRC-E','SRC-SCREEN'],roles=PAY,mode='ファイル選択',dmode='行別確認',process='異動情報アプリのExcelを読み、職員に紐づくデータ内容で重複候補・不備を行別に表示。',reads=['異動情報Excel','既存職員と関連データ'],writes=['取込検証結果（論理記録）'],validation='人の存在だけで重複禁止にしない。照合項目・ファイル様式・一般必須条件は未決。',acceptance=['正常・不備・取込済み／重複可能性を行別に確認できる。'],notes=['勤怠ファイル仕様20列をこの取込へ流用しない。'])
op('OP-IMPORT-APPLY','FUT-IMPORT','行別に取込を判断','E',req=['E-04','E-11','FR-E-01'],src=['SRC-E','SRC-SCREEN'],roles=PAY,mode='行別確認',dmode='取込結果',process='正常行を先に取り込み、問題行は給与班が注意を見て取込／見送りを決める。',reads=['行別検証結果','給与班の判断'],writes=['給与情報の確認待ち候補','行別処理結果'],retained='取込済み行と問題行の結果・識別。',cancel='見送り行は新規反映しない。具体的再取込方法は未決。',notes=['正常行先行可。勤怠の全件検証後反映と混同しない。'])
op('OP-IMPORT-RETURN','FUT-IMPORT','確認待ち候補を開く','E',req=['SCR002-E-001','FUT-IMPORT-001'],src=['SRC-SCREEN','SRC-E'],dest='SCR-002',dtab='勤務条件',dmode='確認待ち',roles=PAY,process='取込結果の対象をSCR-002の確認待ち候補へ引き継ぐ。',reads=['取込対象候補・行別結果'],retained='候補識別子・取込結果。',notes=['取込結果から直接開くボタン・経路は提案。承認済み配置はホーム入口とSCR-002候補確認。'],status=PROPOSED)
op('OP-E-PENDING','SCR-002','確認待ちで絞り込む','E',req=['SCR002-E-001','FUT-STATE-E'],src=['SRC-SCREEN','SRC-E'],dmode='確認待ち',control='提案：給与情報の確認待ち',process='左検索に確認待ち絞込みを追加し、右詳細で不足・不整合を表示。確定後修正で戻った候補も含める。',reads=['認可範囲の候補・確認状態'],notes=['「再確認待ち」という別状態を作らない。'])
op('OP-E-HISTORY','SCR-002','実際の条件変更を登録','勤務条件・控除',req=['PAYREQ-01','PAYREQ-02','PAYREQ-03','PAYREQ-04'],src=['SRC-PAY','SRC-DATA'],tab='勤務条件／社会保険／税固定控除',mode='編集',dmode='登録',process='実際の条件変更は月途中を含む新しい有効期間履歴として登録。発令は勤務条件へ統合し、所属既定予算を個別予算で上書き可能。',reads=['職員基本','旧履歴','日額／時間額単価・所属既定予算'],writes=['勤務条件・保険・税・固定控除の新履歴','職員×控除年月の住民税'],validation='計算対象の採用日は必須。保険未確認／加入／非加入、資格日と控除期間を分ける。固定控除は職員×項目×期間×額。',notes=['月額基本給与、始終業・休憩・週時間、家族個別情報、銀行等は初回対象外。','具体列・入力範囲・期間重複条件は未入力。'])
op('OP-E-CORRECT','SCR-002','誤登録を訂正','E・元データ訂正',req=['E-06','E-08','PAYREQ-03','PAYREQ-04','PAYREQ-07'],src=['SRC-E','SRC-PAY','SRC-CALC'],tab='基本情報／勤務条件／社会保険／税固定控除',mode='登録／確認待ち／確定',dmode='確認待ち',process='原則は局担当が不足・不整合を訂正。給与班も直接訂正可能。誤登録は確定済み履歴も直接訂正でき、前後値を残して再確認へ戻す。',reads=['訂正前の元データ','影響する未払い支給回'],writes=['訂正後元データ・訂正前後履歴','確認待ち状態・影響情報'],validation='実際の条件変更による新履歴と誤登録訂正を区別する。',retained='旧値・処理履歴、戻り先の支給回・職員。',notes=['支払済み結果は更新せず追給・返納へ。未払いは再確認後に再計算・再照合。'])
op('OP-E-SUBMIT','SCR-002','内容を確認待ちにする','E',req=['E-07','E-12','PAYREQ-03','PAYREQ-04'],src=['SRC-E','SRC-PAY'],tab='勤務条件／社会保険／税固定控除',mode='登録／差戻し',dmode='確認待ち',process='勤務条件・保険・税等の内容を給与班の確認待ちにする。局との連絡・調整はアプリ外。',reads=['登録・訂正された内容'],writes=['確認待ち状態'],notes=['必要情報の未確認・未確定を支給確定に使用しない。具体ボタン名は提案。'])
op('OP-E-RETURN','SCR-002','給与情報を差し戻す','E',req=['E-07','E-12','PAYREQ-03','PAYREQ-04'],src=['SRC-E','SRC-PAY'],tab='勤務条件／社会保険／税固定控除',mode='確認待ち',dmode='差戻し',roles=PAY,process='必要な修正を差戻しとし、原則局担当が直して再提出する。',reads=['確認待ちの内容'],writes=['差戻し状態・確認履歴（物理項目未決）'],notes=['2026-09-27の差戻しなし方針はQ18・Q27・R11で更新済み。'])
op('OP-E-CONFIRM','SCR-002','給与情報を確定・再確定','E',req=['E-07','E-08','E-10','PAYREQ-03','PAYREQ-04','PAYREQ-07'],src=['SRC-E','SRC-PAY'],tab='勤務条件／社会保険／税固定控除',mode='確認待ち',dmode='給与班確定',roles=PAY,process='給与班が対象・内容を確認して確定する。訂正後も同じ確認待ちから再確定し、影響する未払い結果を再計算・再照合へ。',reads=['確認待ちデータ','確認履歴'],writes=['給与班確定状態・確認記録'],validation='採用取消・必要情報の未確認は計算利用不可。詳細チェック項目は未入力。',notes=['これは元データ確定。人給差分ゼロ後の支給回確定とは別。'])
# F: same commute tab, known current report route, future certification.
op('OP-F-EDIT','SCR-002','通勤届を入力','F',req=['F-01','F-02','PAYREQ-05'],src=['SRC-F','SRC-PAY'],tab='通勤',mode='入力／差戻し',dmode='入力',roles=LOCAL,process='認定ヘッダーと経路ごとの明細を入力。経路ごとに定期券前払いまたはIC運賃×実通勤日数を選択し混在可能。',reads=['自局職員・旧認定'],writes=['通勤届の入力内容'],validation='通常非常勤職員。調査員はF対象外。詳細必須項目・証憑・算式は未決。',notes=['本人入力は将来追加。現在4経路を新モデルの上限としない。'])
op('OP-F-SUBMIT','SCR-002','通勤届を提出・再提出','F',req=['F-01','F-02','F-03','SCR002-F-001'],src=['SRC-F','SRC-SCREEN'],tab='通勤',mode='入力／差戻し',dmode='提出',roles=LOCAL,process='内容検証後に提出。差戻しは原則提出者が修正し、同じ通勤タブから再提出する。',reads=['通勤届・経路・対象職員'],writes=['提出状態'],failure='不備を表示し認定済みとして計算に使わない。')
op('OP-F-RETURN','SCR-002','通勤届を差し戻す','F',req=['F-03','FUT-STATE-F'],src=['SRC-F','SRC-SCREEN'],tab='通勤',mode='提出',dmode='差戻し',roles=PAY,process='給与班が不備を差戻し状態にし、差戻し理由をアプリ外で提出者へ連絡する。',reads=['提出内容'],writes=['差戻し状態'],notes=['理由の外部連絡を自動送信する機能は追加しない。'])
op('OP-F-CERTIFY','SCR-002','通勤手当を認定','F',req=['F-04','PAYREQ-05'],src=['SRC-F','SRC-PAY'],tab='通勤',mode='提出',dmode='認定',roles=PAY,process='給与班が認定し、計算は認定済みヘッダーと経路を直接参照する。',reads=['提出内容・経路・期間'],writes=['認定情報・認定状態'],notes=['認定額を別給与情報へ重複転記する要件なし。PDFを認定時に自動作成しない。','支給月と期間対応・通勤精算式は未決。'])
op('OP-F-CHANGE','SCR-002','変更届から新認定へ','F',req=['F-07','PAYREQ-05'],src=['SRC-F','SRC-PAY'],tab='通勤',mode='認定',dmode='新たな提出',roles=LOCAL,process='変更届を新たに提出し給与班が再認定。旧認定を残し、精算・追給・返納と関連付ける。',reads=['旧認定・変更後経路'],writes=['新通勤届','新旧認定の関連'],retained='旧認定と当時の経路・期間。')
op('OP-F-NOPAY','SCR-002','一時不支給期間を確認','F',req=['F-08','FR-F-03'],src=['SRC-F','SRC-OPEN'],tab='通勤',mode='認定',dmode='認定',process='病気・欠勤で通勤しない期間は通勤手当を支給しない。認定期間終了と区別する。',reads=['認定期間','病気・欠勤と勤務実績'],writes=['不支給対象期間の記録（方式未決）'],validation='支給月への対応、算定・遡及条件は未入力。',notes=['業務方針は確定。入力部品・記録方式は提案。独立した終了状態にしない。'])
op('OP-F-END','SCR-002','認定期間の終了を確定','F',req=['F-08','FUT-STATE-F'],src=['SRC-F','SRC-SCREEN'],tab='通勤',mode='認定',dmode='認定（期間終了）',roles=PAY,preconditions='局担当から受給要件喪失の届出を受ける。',process='給与班が認定期間の終了を確定する。',reads=['終了届出・認定期間'],writes=['認定期間の終了情報'],notes=['「認定終了」という新しい状態を設けない。一時不支給とは別。'])
op('OP-F-HTML','SCR-002','認定簿を表示','F・帳票',CURRENT,['SCR002-COM-003','FR-F-04'],['SRC-COMMUTE','SRC-STATUS'],dest='EXT-COMMUTE',tab='通勤',dtab='該当なし',control='認定簿表示',enabled='選択職員・保持職員・親職員・認定GUIDが一致。',process='選択認定GUIDだけを別タブHTMLへ渡し、HTML側で親職員と認定を再取得。',reads=['選択認定','親職員・閲覧範囲'],validation='直接URL・古いGUIDでも存在・親・権限を確認。実効認可方式は未決。',failure='不一致・削除済み・権限拒否では帳票本文を出さない。',retained='元の職員・通勤選択。',notes=['通常入口は新様式v1.02への単一入口。旧様式／受入テストボタンを復活させない。','将来は給与班全対象・局担当自局。新モデルの取得契約はPD-09。'])
op('OP-F-PDF','EXT-COMMUTE','ブラウザー印刷でPDF保存','F・帳票',CURRENT,['SCR002-COM-003','F-05'],['SRC-COMMUTE','SRC-STATUS'],control='ブラウザーの印刷',method='利用者が印刷を開きPDF保存',process='A4横2ページを1つのPDFとして保存する。枠超過なら印刷停止・警告。',reads=['現在の認定簿HTML'],writes=['利用者が保存するPDFファイル'],validation='NULLと0を区別。71表示欄、選択認定、用紙向きとページ数。',cancel='印刷を閉じても認定データは変更しない。',notes=['認定時の自動PDF作成はしない。実機個別印刷設定の全条件合格を意味しない。'])
op('OP-F-RETURN-HTML','EXT-COMMUTE','元の通勤タブへ戻る','F・帳票',CURRENT,['SCR002-COM-003'],['SRC-COMMUTE'],dest='SCR-002',dtab='通勤',control='元のアプリタブを選択',method='ブラウザーで元タブに切替（必要時に帳票タブを閉じる）',process='元のSCR-002通勤タブへ戻る。',reads=['元画面コンテキスト'],retained='職員・認定選択。',writes=[])
# G excludes electronic filing and automated import.
op('OP-G-REGISTER','SCR-002','外部決定結果を登録','G',req=['G-01','G-02','G-04','G-06','SCR002-G-001','SCR002-G-002'],src=['SRC-G','SRC-SCREEN','SRC-PAY'],tab='社会保険／税固定控除',mode='編集',dmode='登録（確認待ち）',process='紙・電子で受領した外部機関の決定結果を担当局または給与班が手入力する。住民税は税固定控除、共済・保険・ハローワークは社会保険。',reads=['外部機関の決定結果','対象職員'],writes=['決定結果と確認待ち状態'],validation='決定内容を正とする。証憑保存・具体項目は未入力。',notes=['電子申請操作、自動結果取込、申請・受付進捗は作らない。','二重申請防止方法は未決。'])
op('OP-G-CONFIRM','SCR-002','外部決定結果を確認確定','G',req=['G-05','SCR002-G-004','PAYREQ-04'],src=['SRC-G','SRC-PAY'],tab='社会保険／税固定控除',mode='登録（確認待ち）',dmode='確定',roles=PAY,process='給与班が決定内容・対象職員を確認して確定する。給与へ影響する内容はそれまで使わない。',reads=['外部決定の登録内容'],writes=['確認確定状態'],validation='必要情報の未確認を支給確定へ流さない。制度の自動判定は初回対象外。',notes=['給与班が外部決定の採否を決め直す工程は設けない。'])
# Confirmed payroll business, expressly proposed placement.
op('OP-PAY-PERIOD','FUT-JLINK','支給回・対象期間を設定','給与計算',PROPOSED,['PAYREQ-07','PERIOD-01','PERIOD-02'],['SRC-PAY','SRC-IF','SRC-OPEN'],tab='支給回の状況',roles=PAY,process='支給対象期間と支給日を別管理し、通常既定と例外変更を扱う。月末締め翌月支給。',reads=['職員・支給対象期間・支給日'],writes=['支給回の期間・支給日（論理記録）'],validation='対象日具体ルールと採用境界は未入力。',notes=['業務契約は確定。支給回作成・編集を人給連携に置く配置は提案であり承認済みモックの追加確定ではない。'])
op('OP-PAY-CALCULATE','FUT-JLINK','給与を計算・再計算','給与計算',PROPOSED,['PAYREQ-07','PAYREQ-08','PAYREQ-10'],['SRC-PAY','SRC-CALC','SRC-OPEN'],tab='支給回の状況',roles=PAY,dmode='計算済み',preconditions='必要な勤務条件・控除・勤怠・通勤が確認済み／認定済みで、取込不完全でない。',process='給与班が計算版を実行。複数所属の実績は職員ごとに集計し、結果と使用条件・単価・率・入力値を版別に保持する。',reads=['確認済み勤務条件・勤務実績','認定済み通勤','登録済み保険・税・控除','日額／時間額単価・期末勤勉別率・調整'],writes=['計算版・職員別結果・使用根拠'],reset='未払いの入力／結果更新で旧照合ゼロを失効。',failure='未確認・不完全・式未確定を確定結果として採用しない。',notes=['業務要件は確定、画面配置と部品は提案。現行SCR-005仮例とは別機能。','D9以降の式・端数・符号を推測しない。'])
op('OP-PAY-ADJUST','FUT-JLINK','例外調整を記録','給与計算',PROPOSED,['PAYREQ-07'],['SRC-PAY','SRC-CALC'],tab='支給回の状況',roles=PAY,process='例外・追給・返納は計算額と別の調整記録に対象・項目・額・理由・処理者を保存する。',reads=['元計算結果・対象支給回'],writes=['調整記録・理由・処理者'],reset='影響する未払い結果と照合を再処理対象にする。',validation='元データ誤りは元データ訂正を原則とし、結果上書きで隠さない。',notes=['業務契約は確定。入力画面配置・額の許容条件は未決。'])
op('OP-PAY-INDIVIDUAL','FUT-JLINK','個別・所属一括確定の境界','給与確定',UNDECIDED,['PAYREQ-07','JLINK-UI-11','I12'],['SRC-PAY','SRC-JDETAIL','SRC-OPEN'],tab='支給回の状況',roles=PAY,process='職員×支給回の個別確定と所属単位一括確定の業務要件は維持する。I12の支給回全体最新ゼロ判定との操作分担は詳細未入力。',reads=['職員別・所属別状態','支給回全体の最新照合'],writes=[],enabled='未決の操作分担を確定するまで実行可能操作として扱わない。',notes=['表示フィルター・個別選択でI12の全体確定条件を狭めない。HTMLでは未決説明のみ。'])
op('OP-PAY-PAID','FUT-JLINK','支払い済みを記録','支払実績',PROPOSED,['PAYREQ-08','PAYREQ-10'],['SRC-PAY','SRC-IF','SRC-CALC'],tab='支給回の状況',mode='給与班確定',dmode='支払い済み',roles=PAY,preconditions='給与班確定済みで、外部での支払実施を確認できること。記録項目・証跡条件は未入力。',process='給与班確定とは別に支払い済みを記録する。アプリが銀行送金など実際の支払いを実行する要件はない。',reads=['確定結果','支払実績'],writes=['支払い済み状態・支払実績'],retained='最終結果・最終根拠・給与簿・支払実績・各照合回の不一致明細。',notes=['業務状態は確定。記録ボタン配置・証跡入力は提案。','支払済み結果は訂正不可。過去誤りは別追給・返納。中間版削除権限・時期・保存期間はPD-06。'])
# JLINK I1-I12 exact behavioral contract.
op('OP-JLINK-SELECT','FUT-JLINK','支給回・タブを選択','人給連携',req=['JLINK-UI-01','JLINK-UI-02','I3','I5'],src=['SRC-JSCREEN','SRC-I','SRC-JDETAIL'],tab='支給回の状況／出力／取込・照合',roles=PAY,control='支給回選択／3タブ',process='選択支給回の支給日・対象期間・状態を共通表示し3タブを切替える。',reads=['支給回・最新結果・取込照合状態'],retained='タブ間の支給回。',notes=['照合対象の計算版選択を置かない。I1～I3はモック承認による確定。'])
op('OP-JLINK-TARGET','FUT-JLINK','出力対象を選択','人給連携',req=['JLINK-UI-03','I1','I9'],src=['SRC-JSCREEN','SRC-I','SRC-JDETAIL'],tab='出力',roles=PAY,control='職員絞込み／明細選択',process='初回は支給回の全職員を既定対象にし、職員で絞れる。差分再出力では対応明細のみを初期選択し変更可能。',reads=['最新計算結果の出力明細','差分と出力明細の対応'],writes=['画面内の出力対象選択'],row_scope='表示・出力対象のみ。確定判定の支給回全体範囲は縮小しない。',notes=['差分1項目＝Excel1行とは限らない。対応・多重行集約はPD-03。'])
op('OP-JLINK-AM','FUT-JLINK','A/Mを指定','人給連携',req=['JLINK-UI-04','IF-05','I2'],src=['SRC-JSCREEN','SRC-IF','SRC-I'],tab='出力',roles=PAY,control='更新区分の一括指定／明細変更',process='職員がA/Mを一括指定し、明細ごとに変更する。初回A・不一致修正Mは人が判断する。',reads=['出力対象明細','利用者指定'],writes=['明細別指定A/M'],validation='再出力だからといって自動でMに変えない。',notes=['D（削除）出力は未決。'])
op('OP-JLINK-EXPORT','FUT-JLINK','確認してExcel出力','人給連携',req=['JLINK-UI-05','I4','IF-01','IF-02','IF-03','IF-04','IF-06','IF-07','IF-08'],src=['SRC-JSCREEN','SRC-JDETAIL','SRC-IF','SRC-TEST'],dest='EXT-JINKYU',tab='出力',dtab='外部取込',roles=PAY,control='出力前確認→Excel出力',preconditions='支給回・人数・明細数・A/M件数を利用者が確認。',validation='237列A～IC、固定見出し1行目、データ2行目、文字列型・表示形式、12桁番号と日付yyyy/mm/dd、11キー。',process='その時点の最新版計算結果からxlsxを生成し、計算版・対象明細・指定A/Mを処理履歴に結ぶ。職員が外部人給へ渡す。',reads=['最新版計算結果','指定対象・A/M','既存237列見出し'],writes=['出力xlsx','出力履歴'],cancel='確認画面で取り消した場合は出力しない（画面実装案）。',notes=['人給取込で空欄は0となり既存値保持指定には使えない。網掛け名称列も固定列から除かない。','人給キー：B職員番号、D支給年月日、E対象年月日、F業務区分、H併任区分、J組織コード、M非常勤支出科目、Q判別区分、S短時間職員、U支払処理、W実績区分。','Excel生成・配布先・約800件性能は未決。給与簿照合キーを11キーと断定しない。'])
op('OP-JINKYU-PROCESS','EXT-JINKYU','人給取込・給与簿出力','人給外部処理',req=['IF-01','IF-09','I10','PAYREQ-08'],src=['SRC-IF','SRC-JDETAIL'],dest='FUT-JLINK',tab='外部処理',dtab='取込・照合',roles=PAY,control='外部人給システムの操作',method='職員が外部システムで実行。アプリ自動接続は未決。',process='xlsxを人給へ取り込み必要な人給処理を行い、人給給与簿CSVを出力してアプリへ戻す。',reads=['計算結果xlsx','人給側データ'],writes=['外部人給データ（実行は別システム）','給与簿CSV'],failure='人給側のエラーはI8で表示要件あり。結果取得方式は未決。',notes=['このモデル・HTMLで外部取込成功を実測・証明しない。','成功／一部失敗／失敗をアプリへ手入力する操作なし。'])
op('OP-JLINK-IMPORT','FUT-JLINK','給与簿CSVを取り込む','人給連携',req=['JLINK-UI-06','IF-09','IF-10','I5','I10'],src=['SRC-JSCREEN','SRC-IF','SRC-JDETAIL'],tab='取込・照合',roles=PAY,control='給与簿CSV取込',process='1～5行を固定領域、6行目以降を明細とし、可変位置の【合計情報】を境界に明細を取り込む。合計情報のチェック・保存は不要。',reads=['人給給与簿CSV'],writes=['給与簿取込回・読取り専用明細・原値'],validation='未知職員を保持・表示して確定を停止。CSV読取設定と照合キー・行対応は未入力。',failure='失敗時は前回成功分を維持し、失敗を最新成功として扱わない。',retained='元の空欄と取込回。',notes=['人給への出力xlsxと戻りCSVを混同しない。給与簿を直接編集しない。'])
op('OP-JLINK-RECONCILE','FUT-JLINK','最新版と照合','人給連携',req=['JLINK-UI-06','JLINK-UI-07','I5','I7','PAYREQ-08'],src=['SRC-JDETAIL','SRC-IF','SRC-PAY','SRC-TEST'],tab='取込・照合',roles=PAY,dmode='照合中→差分ゼロ確認／差分あり',control='照合',process='成功取込給与簿と支給回の最新版計算結果を職員・支給回の項目・合計・欠落・余分・重複まで照合。日時・実行者・件数・双方額・差額を処理回別に保存。',reads=['選択支給回の最新版計算結果','成功した給与簿取込回'],writes=['照合処理・不一致明細・最新結果識別'],validation='数値比較は空欄を0とし原値は保持。未知・欠落・余分・重複を未解決のままゼロにしない。',reset='開始中／完了後に結果が変われば旧差分ゼロは失効。',success='一致状況を確認する。人給取込の成功証明ではない。',notes=['出力後変更時の通知は「出力後に計算結果が変更されています」。','古い出力版へ戻して一致を作らない。更新検出・確定時再検証の物理方式未決。'])
op('OP-JLINK-FILTER','FUT-JLINK','差分・全件表示を切替','人給連携',req=['JLINK-UI-08','I6','I11'],src=['SRC-I','SRC-JSCREEN'],tab='取込・照合',roles=PAY,control='差分のみ／全件',process='初期は差分のみ。全件表示へ切替え可能。6列：職員・対象期間・項目・アプリ値・給与簿値・差額。',reads=['照合結果'],writes=['画面表示条件'],retained='照合結果の全件と支給回。',row_scope='表示範囲だけを変更。確定範囲は全支給回。',notes=['差額の符号・非数値差分の表示方法は未入力。'])
op('OP-JLINK-CORRECT','FUT-JLINK','差分原因の入力画面へ','人給連携',req=['JLINK-UI-09','IF-10','PAYREQ-07'],src=['SRC-JSCREEN','SRC-JDETAIL'],dest='SCR-002',tab='取込・照合',dtab='原因に応じた勤務条件／通勤／控除',roles=PAY,control='差分の原因に応じた訂正動線',process='勤務条件・通勤・控除ならSCR-002、勤怠ならSCR-003へ。元データ訂正→再確認／再提出→再計算を経て戻る。人給原因は外部人給で訂正。',reads=['差分・対象職員・支給回'],retained='往復の支給回・職員。',reset='元データ変更時に未払いの旧計算・照合を失効。',notes=['destination_screen_idは代表SCR-002。勤怠SCR-003／外部EXT-JINKYUは原因別分岐。','給与簿直接訂正なし。支払済みはSCR-007の別追給・返納へ。'])
op('OP-JLINK-REEXPORT','FUT-JLINK','差分対応明細を再出力','人給連携',req=['JLINK-UI-03','I9','I2','I4'],src=['SRC-I','SRC-JDETAIL','SRC-TEST'],tab='取込・照合',dtab='出力',roles=PAY,process='差分に対応する出力明細のみを初期選択し、利用者が対象・A/Mを変更して、出力前確認からExcelを再生成する。',reads=['差分と出力明細の対応','最新版結果'],writes=['出力対象・指定A/M・再出力履歴'],validation='同一明細に複数差分が対応しても重複出力しない。差分行をそのままExcel行にしない。',notes=['行対応未特定時の操作は未決。再出力でMを自動指定しない。'])
op('OP-JLINK-ERROR','FUT-JLINK','人給エラー行を確認','人給連携',req=['JLINK-UI-10','IF-11','I8'],src=['SRC-I','SRC-JDETAIL','SRC-OPEN'],tab='取込・照合',roles=PAY,process='人給のエラー対象行をアプリで分かるようにする。',reads=['人給エラー情報（取得方式未入力）'],writes=[],enabled='表示要件のみ確定。エラー形式・取得方法・明細関連が決まるまで実装方式は未決。',notes=['給与簿CSV解析エラーと人給インポートエラーを区別。','直接接続、自動エラー取込、必須エラーファイル、手入力方式のいずれも確定しない。'])
op('OP-JLINK-CONFIRM','FUT-JLINK','給与班が支給回を確定','人給連携',req=['JLINK-UI-11','I12','PAYREQ-07','PAYREQ-08'],src=['SRC-JSCREEN','SRC-I','SRC-JDETAIL','SRC-TEST'],tab='支給回の状況',mode='最新照合・差分ゼロ確認',dmode='給与班確定',roles=PAY,control='確定',preconditions='支給回全体の最新照合が差分ゼロで未解決行がない。',validation='権限・全支給回の最新版・未知職員／欠落／余分／重複／未確認必要情報を確定時に検証。',process='給与班が確定ボタンで確定する。確認ダイアログは出さない。ゼロだけで自動確定しない。',reads=['支給回全体の最新計算識別・照合','必要情報の確定状態'],writes=['給与班確定状態・履歴'],row_scope='表示・職員絞込みにかかわらず支給回全体。',enabled='全体最新ゼロ・未解決なし・給与班権限ありのみ。',failure='古いゼロ・変更・権限不足・未解決を検出したら確定せず再照合へ。',cancel='確認ダイアログはない。確定後取消の具体条件は未入力。',notes=['I4のExcel出力前確認は残る。I12とは別操作。','確定と支払い済み記録は別。'])
op('OP-JLINK-HISTORY','FUT-JLINK','処理回の履歴を確認','人給連携',req=['PAYREQ-08','PAYREQ-10','IF-12'],src=['SRC-PAY','SRC-CALC','SRC-JDETAIL'],tab='支給回の状況',roles=PAY,process='計算版・出力・取込回・照合の履歴と不一致明細を参照する。',reads=['各処理回の日時・実行者・件数・状態','双方額・差額','最終結果・最終根拠・給与簿・支払実績'],retained='中間版削除後も照合識別・不一致双方額を保持。',notes=['履歴参照の配置は提案。照合対象の計算版を選ぶ操作とは異なる。','Excel／CSV自体の継続保存は必須でない。保存期間・削除時点・権限はPD-06。'])
op('OP-JLINK-HOME','FUT-JLINK','ホームへ戻る','人給連携',PROPOSED,['JLINK-UI-01','COMMON-CONTEXT-001'],['SRC-JSCREEN','SRC-OPEN'],dest='SCR-001',tab='任意の人給タブ',dtab='該当なし',roles=PAY,process='ホームへ戻る。未実行出力対象やA/Mの保存・破棄方法は詳細未決。',reads=['支給回・画面選択'],unsaved='提案：未保存指定があれば保存せず移動する前に確認。確定操作I12には追加ダイアログを設けない。')
# Retroactive differences and repayment; screen location remains bounded.
op('OP-RETRO-CALCULATE','SCR-007','過去月との差額を計算','遡及差額',req=['PAY-03','FR-PAY-01','PAYREQ-08'],src=['SRC-AUTH','SRC-PAY','SRC-OPEN'],mode='対象選択',dmode='確認待ち',roles=PAY,process='既確定・支払済み結果を保持し、改定ルールまたは訂正後の再計算との差額を月別・項目別に作る。',reads=['過去の確定結果','訂正後条件・改定ルール・最終根拠'],writes=['月別差額内訳・確認待ち結果'],validation='式・端数・境界はPD-02。旧支払結果を上書きしない。',notes=['SCR-007は独立確認画面の仮ID。計算起動の配置と入口は提案。'])
op('OP-RETRO-CONFIRM','SCR-007','差額内訳を確認・確定','遡及差額',req=['PAY-04','SCR007-DIFF-001','FUT-STATE-PAY'],src=['SRC-AUTH','SRC-SCREEN','SRC-PAY'],mode='確認待ち',dmode='確定',roles=PAY,process='対象職員の計算結果を一覧選択し、月別・項目別の旧結果／訂正後／差額を確認して給与班が確定する。',reads=['差額内訳・元支払'],writes=['差額確定状態・確認履歴'],validation='確定前は支給・返納へ反映しない。',notes=['支給・返納実施結果を差額状態に追加しない。SCR-002へのタブ統合はD-08未決。'])
op('OP-RETRO-EXPORT','SCR-007','追給を人給出力へ渡す','追給',req=['PAYREQ-08','PERIOD-04','PERIOD-05'],src=['SRC-PAY','SRC-IF','SRC-I','SRC-OPEN'],dest='FUT-JLINK',dtab='出力',mode='差額確定',roles=PAY,process='複数過去月追給を人給の追給行へ集約し、アプリ内に月別差額と出力行の対応を保持する。',reads=['確定済み月別差額'],writes=['集約追給と月別内訳の対応'],validation='対象年月日は差額発生対象期間。R10集約とD7/D8の対象日を両立する具体方式は未決。',notes=['常に1職員2行、sgが追給、代表月／代表日採用、11キーが給与簿照合キーとは断定しない。','D9～D12未回答・保留。D1～D8以外の式を確定しない。'])
op('OP-REPAY-METHOD','SCR-007','返納方法を決定','返納',PROPOSED,['PAY-05','PAYREQ-08'],['SRC-AUTH','SRC-PAY','SRC-OPEN'],mode='差額確定',roles=PAY,process='給与班が給与相殺・納入告知書を選ぶ。分割回収と両方法併用を認め、元支払と返納案件を関連付ける。',reads=['確定差額・元支払'],writes=['返納案件・方法・額・状態'],validation='相殺限度・告知書生成・取消・過回収・完了判定はPD-07未決。',notes=['業務契約は確定。返納入力をSCR-007に置く配置は提案。'])
op('OP-REPAY-RECORD','SCR-007','回収実績と残額を記録','返納',PROPOSED,['PAYREQ-08','PAY-05'],['SRC-PAY','SRC-AUTH','SRC-OPEN'],roles=PAY,process='案件に複数の回収実績を結び、回収済額と残額を確認する。支払済み給与を訂正しない。',reads=['返納案件','既回収実績'],writes=['今回回収実績・回収済額・残額'],validation='取消・過回収・完了判定条件は未決。方法併用・分割を保持。',notes=['業務契約は確定。記録UI配置は提案。実際の徴収・送金をHTMLで実行しない。'])
# Additional visible mock controls requested by the renderer; unapproved routes
# are item-level proposals, never promoted by the global review status.
op('OP-002-CLEAR','SCR-002','検索条件をクリア','職員検索',PROPOSED,['SCR002-LT-002','SCR002-UI-004'],['SRC-SCREEN','SRC-DETAIL','SRC-OPEN'],control='検索条件をクリア',process='レビュー案として検索入力・条件を初期状態へ戻す。再検索・選択解除のタイミングは未確定。',reads=['画面内の検索入力・確定条件'],writes=['画面内の検索条件'],retained='未保存入力を勝手に破棄しない。',reset='提案：検索入力・選択条件のみ。旧職員消去は正常0件／職員変更時の確定契約に従う。',notes=['既存ソースにクリア操作の履歴があるが、最新版の全挙動を設計記述だけで確定しない。'])
op('OP-002-FONT','SCR-002','文字サイズを切替','表示調整',CURRENT,['SCR002-UI-003'],['SRC-SCREEN','SRC-DETAIL'],control='文字：標準／文字：大',process='ヘッダー直下の操作領域で文字サイズを切替える。',reads=['文字サイズ表示状態'],writes=['画面内の文字サイズ状態'],retained='対象職員・検索条件・選択履歴・未保存入力。',reset='業務データのリセットなし。',notes=['具体サイズ・各画面への共有範囲の検証は別。'])
op('OP-IMPORT-HOME','FUT-IMPORT','ホームへ戻る','E',PROPOSED,['FUT-IMPORT-001','COMMON-CONTEXT-001'],['SRC-SCREEN','SRC-OPEN'],dest='SCR-001',roles=PAY,control='提案：ホーム',process='E一括取込画面からホームへ戻る。実行済み行の取込を巻き戻さない。',reads=['取込結果・未処理行の選択'],retained='反映済み候補と処理結果。',unsaved='提案：未処理の行選択や判断があれば移動前に確認。取消なら同画面へ。',notes=['詳細な戻り・中断・再開方式は未決。'])
op('OP-001-DIFF','SCR-001','遡及差額を開く','遡及差額',PROPOSED,['SCR007-DIFF-001'],['SRC-SCREEN','SRC-OPEN'],dest='SCR-007',roles=PAY,control='提案：遡及差額',process='独立した遡及差額画面を開くレビュー用入口。',reads=['ログイン主体・利用範囲'],notes=['独立画面先行は確定。ホーム入口は未承認の配置案で、現行4主ボタンに実装済みとはしない。'])
op('OP-007-HOME','SCR-007','ホームへ戻る','遡及差額',PROPOSED,['SCR007-DIFF-001','COMMON-CONTEXT-001'],['SRC-SCREEN','SRC-OPEN'],dest='SCR-001',roles=PAY,control='提案：ホーム',process='レビュー用のホームへの復路。差額確定・回収実績を書き換えない。',reads=['選択差額・回収入力状態'],unsaved='提案：未保存の調整・回収入力は移動前に確認し、取消なら保持。',notes=['入口と復路の具体配置・保存中断条件は未決。'])
op('OP-JLINK-CORRECT-ATT','FUT-JLINK','勤怠の差分訂正へ','人給連携',req=['JLINK-UI-09','PAYREQ-06','PAYREQ-07'],src=['SRC-JSCREEN','SRC-JDETAIL','SRC-PAY'],dest='SCR-003',tab='取込・照合',dtab='該当なし',roles=PAY,control='提案：勤務時間を確認',process='差分原因が勤怠なら勤務時間報告へ進む。報告済みは給与班が差戻してから訂正・再提出する。',reads=['差分・職員・支給回・勤務月'],retained='支給回・職員・戻り先。',reset='訂正後に影響する未払いの計算・照合を失効。',notes=['動線は確定。具体ボタン名、対象報告の選択方法は提案。'])
op('OP-JLINK-RETURN','SCR-002','人給連携へ戻る','人給連携',req=['JLINK-UI-09'],src=['SRC-JSCREEN','SRC-JDETAIL'],dest='FUT-JLINK',tab='勤務条件／通勤／社会保険／税固定控除',dtab='取込・照合',roles=PAY,control='提案：人給連携へ戻る',process='訂正経路から支給回・職員を保持して人給連携へ戻る。更新された元データは再確認・再計算・再照合が必要。',reads=['戻り先の支給回・職員','保存・確認状態'],retained='支給回・職員。',unsaved='SCR-002の破棄確認を適用。取消なら現在の入力を保持。',notes=['戻り時に古い差分ゼロを復活させない。'])
op('OP-JLINK-RETURN-ATT','SCR-003','人給連携へ戻る','人給連携',req=['JLINK-UI-09','PAYREQ-06'],src=['SRC-JSCREEN','SRC-JDETAIL','SRC-UIOCT'],dest='FUT-JLINK',dtab='取込・照合',roles=PAY,control='提案：人給連携へ戻る',process='勤怠訂正経路から支給回・職員を保持して戻る。保存・再提出・再計算が必要な状態を見落とさない。',reads=['戻り先の支給回・職員','報告の状態'],retained='支給回・職員。',enabled='編集中は移動不可。保存成功または読取り切替の破棄確認後。',unsaved='SCR-003の読取り切替時の破棄確認を適用。取消なら入力保持。',notes=['具体的な復路コントロールは提案。'])

# Existing PoC is an observed boundary outside the numbered six-screen contract.
source('SRC-POCNAV','src/screen-ui/v1.30/home.paste.yaml','現行ホームのPoC入口','Button3.Text／OnSelect（scrExcelImportPocへの遷移）')
screen('CUR-IMPORT-POC','PoCデータ一括取込（現行）',CURRENT,'現行ホームの4主ボタン下にある既存PoCへの入口。給与登録Eの専用取込とは区別する。',[],USER,['COMMON-SCREEN-001'],['SRC-UIOCT','SRC-POCNAV','SRC-OPEN'],['レビュー上の補助ID。正式SCR-001～006の画面一覧を変更するものではない。','現行ソースの遷移先はscrExcelImportPoc。内部項目・保存操作の仕様をこのレビューで新たに確定しない。','FUT-IMPORTの正常行先行取込や勤怠追加更新の業務仕様をPoCに転記しない。','PoC内部の機能・復路は本レビューの参照資料から未照合。画面は境界説明のみとする。'])
op('OP-001-POC','SCR-001','PoCデータ一括取込','現行PoC境界',CURRENT,['COMMON-NAV-001'],['SRC-UIOCT','SRC-POCNAV'],dest='CUR-IMPORT-POC',roles=USER,control='PoCデータ一括取込',process='4主ボタンの下にある現行ボタンから既存scrExcelImportPocへ移動する。',reads=['ログイン主体'],notes=['FUT-IMPORTの入口ではない。内部取込の実行・更新仕様はここでは未照合。'])
op('OP-POC-HOME','CUR-IMPORT-POC','ホームへ戻る','現行PoC境界',PROPOSED,['COMMON-CONTEXT-001'],['SRC-UIOCT','SRC-POCNAV','SRC-OPEN'],dest='SCR-001',roles=USER,control='提案：ホーム（レビュー用復路）',process='レビュー画面からホームへ戻る境界リンク。現行PoCの実際の復路部品は未照合。',reads=['画面コンテキスト'],unsaved='PoC内部の未保存・処理中の扱いは未入力。実運用の中断処理として扱わない。',notes=['実装済み復路と断定しない。PoC内の取込はこのレビューでは実行しない。'])

# Separate readable business diagrams. Blank screen/op IDs identify an external
# boundary or a business decision, never an invented Canvas screen.
workflows=[]
def wf(id,name,actor,start,end,status,screen_ids,req,src,steps,edges):
    workflows.append(dict(id=id,name=name,actor=actor,start=start,end=end,status=status,screen_ids=screen_ids,requirements=req,source_ids=src,steps=[dict(id=s[0],label=s[1],screen_id=s[2],operation_id=s[3],kind=s[4],detail=s[5]) for s in steps],edges=[dict(from_=e[0],to=e[1],label=e[2]) for e in edges]))
wf('WF-01','職員検索・編集・画面往復','ログイン利用者','ホームから職員検索','保存済み読取り、または移動取消',CONFIRMED,['SCR-001','SCR-002','SCR-005'],['COMMON-NAV-003','SCR002-EDIT-001','SCR002-EDIT-002','SCR002-EDIT-003'],['SRC-UIOCT','SRC-DETAIL','SRC-OPEN'],[
('a','ホームから職員検索','SCR-001','OP-001-STAFF','start','支給明細へのホーム直接導線はない。'),('b','条件を指定して検索','SCR-002','OP-002-SEARCH','action','0件は旧職員・履歴・帳票を消去。権限／通信失敗は区別。'),('c','職員・タブ・履歴を選ぶ','SCR-002','OP-002-SELECT','action','6タブを保持し給与簿は常時読取り専用。'),('d','許可項目を編集','SCR-002','OP-002-EDIT','action','タブ切替で入力を保持。保存機能の全区分実測は未確認。'),('e','保存か移動か','SCR-002','','decision','保存または未保存を伴う職員／画面／読取り切替。'),('f','保存・再取得','SCR-002','OP-002-SAVE','action','再取得で一致した後だけ読取りへ。失敗は入力保持。'),('g','変更破棄を確認','SCR-002','OP-002-READMODE','decision','未保存なら確認。常設破棄ボタンは置かない。'),('h','取消して編集続行','SCR-002','OP-002-CANCEL','action','現在の職員・履歴・入力を保持。'),('i','破棄後に支給明細へ','SCR-002','OP-002-PAYDETAIL','action','続行選択後だけ破棄。職員・対象月を渡す。'),('j','職員詳細へ戻る','SCR-005','OP-005-RETURN','end','受け手で存在・所属を再確認。検索結果保持には現行差分あり。')],
[('a','b','開く'),('b','c','検索結果あり'),('b','b','0件／失敗後に再検索'),('c','d','編集'),('d','e','操作選択'),('e','f','保存'),('f','d','保存失敗・入力保持'),('f','c','成功'),('e','g','未保存で移動'),('g','h','取消'),('h','d','入力保持'),('g','i','破棄して続行'),('i','j','試算後に戻る'),('j','c','職員・月を保持')])
wf('WF-02','A～D 採用候補の受渡し','秘書課・前工程担当・給与班','通常職員の初任給確定、または調査員のC開始','同じ候補に発行番号を反映',CONFIRMED,['FUT-IMPORT','SCR-002','SCR-006'],['AD-01','AD-02','AD-03','AD-04','AD-05','AD-09','FR-AD-01','FR-AD-02'],['SRC-AD','SRC-FR','SRC-PAY','SRC-OPEN'],[
('a','通常職員の初任給確定','','','start','A。秘書課の確定前情報は渡さない。'),('b','採用起案の決裁','','','external','B。決裁だけでは候補を作らない。'),('i','調査員はCから開始','','','start','調査員にA・Bを適用しない。'),('c','発令情報の登録完了','','','external','C。通常職員・調査員ともこの時点を通知起点にする。'),('d','確認待ち候補を作成','FUT-IMPORT','OP-AD-CANDIDATE','action','自動通知・作成は目標。調査員は採用日でルール版選択。'),('e','給与班が確認・確定','SCR-002','OP-E-CONFIRM','action','職員番号発行を候補作成・確認確定の前提にしない。'),('f','職員番号を発行','','','external','Dは候補作成と並行した後続工程。'),('g','同じ候補へ番号反映','SCR-002','OP-AD-NUMBER','action','採用ごとの識別子で自動反映を目標。手動紐づけ操作は設けない。'),('h','番号と候補の整合を確認','SCR-002','','end','再採用は新しい採用識別子。一人一行基本との統合はPD-08。')],
[('a','b','確定後'),('b','c','決裁後'),('i','c','直接開始'),('c','d','通知・連携方式未決'),('d','e','確認'),('c','f','番号発行へ'),('f','g','番号発行後'),('d','g','同じ候補'),('g','h','対応確認'),('e','h','確認状態を保持')])
wf('WF-03','A～D 決裁後変更・採用取消','秘書課・給与班','前工程で変更または取消','再確定、または履歴を残して計算除外',CONFIRMED,['SCR-002'],['AD-06','AD-07','AD-08','E-08','E-09'],['SRC-AD','SRC-E','SRC-PAY'],[
('a','変更・取消情報を受領','SCR-002','','start','自動受領方式は未決。採用取消は給与支給前のみ。'),('b','変更か採用取消か','SCR-002','','decision','確認待ち／確定のどちらも取消対象。'),('c','変更前の内容を保持','SCR-002','OP-AD-CHANGE','action','実際の変更と誤登録訂正を区別。'),('d','給与班修正値と相違か','SCR-002','','decision','上流変更で給与班の値を自動上書きしない。'),('e','採用値を給与班が判断','SCR-002','OP-AD-CHANGE','action','採用値・変更前後を残す。'),('f','確認待ちへ戻し再確定','SCR-002','OP-E-CONFIRM','end','再確定まで計算へ使用しない。未払いに影響すれば再計算。'),('g','候補を採用取消にする','SCR-002','OP-AD-CANCEL','action','候補を削除せず履歴保持。'),('h','給与計算から除外','SCR-002','','end','採用取消に伴う既支給返納は要件外。')],
[('a','b','判定'),('b','c','変更'),('c','d','比較'),('d','e','相違あり'),('d','f','相違なし'),('e','f','判断後'),('b','g','取消'),('g','h','履歴保持')])
wf('WF-04','E Excel一括取込と行別判断','会計課給与班','ホームのデータ一括取込み','確認待ち候補と行別結果',CONFIRMED,['SCR-001','FUT-IMPORT','SCR-002'],['E-02','E-03','E-04','E-11','FUT-IMPORT-001'],['SRC-E','SRC-SCREEN'],[
('a','データ一括取込みを開く','SCR-001','OP-001-IMPORT','start','専用画面。現行PoCとは別。'),('b','Excelを選び行検証','FUT-IMPORT','OP-IMPORT-VALIDATE','action','形式・列・一般検証詳細は未決。'),('c','不備・重複候補があるか','FUT-IMPORT','','decision','人の存在だけで一律禁止しない。内容を比較。'),('d','正常行を先に取込','FUT-IMPORT','OP-IMPORT-APPLY','action','問題のない行は先行反映可能。'),('e','問題行を給与班が判断','FUT-IMPORT','OP-IMPORT-APPLY','decision','取込済み・重複可能性等の注意を確認。'),('f','確認待ち候補を作成','FUT-IMPORT','OP-IMPORT-APPLY','action','行別の処理結果を保持。'),('g','その行の取込を見送る','FUT-IMPORT','','end','問題行だけ見送り。再取込手順は未決。'),('h','不足を確認・訂正','SCR-002','OP-E-CORRECT','end','候補選択はSCR-002左検索、確認は右詳細。')],
[('a','b','開始'),('b','c','検証完了'),('b','b','読取失敗・再選択'),('c','d','正常行'),('c','e','問題行'),('d','f','反映'),('e','f','取り込む'),('e','g','見送る'),('f','h','確認待ちへ')])
wf('WF-05','E 条件・控除の確認と訂正','局担当者・給与班','新規・実際変更・誤登録訂正','給与班確定後の未払い再計算',CONFIRMED,['SCR-002','FUT-JLINK'],['E-06','E-07','E-08','E-10','E-12','PAYREQ-03','PAYREQ-04','PAYREQ-07'],['SRC-E','SRC-PAY','SRC-CALC'],[
('a','登録・変更・訂正が必要','SCR-002','','start','基本は最新値、給与条件・所属・控除は期間履歴。'),('b','実際変更か誤登録か','SCR-002','','decision','月途中の実際変更と誤りの訂正を分ける。'),('c','新しい有効期間履歴','SCR-002','OP-E-HISTORY','action','勤務条件に発令を統合。保険資格日と控除期間を分ける。'),('d','前後値を残して訂正','SCR-002','OP-E-CORRECT','action','確定済み履歴も誤登録訂正可。再確認まで計算に反映しない。'),('e','確認待ちに提出','SCR-002','OP-E-SUBMIT','action','保険未確認と非加入を区別。'),('f','給与班が内容を確認','SCR-002','','decision','必要条件の未確定は支給確定不可。'),('g','差戻し・不足修正','SCR-002','OP-E-RETURN','action','原則局担当、給与班の直接修正も可能。連絡調整は外部。'),('h','給与班が確定・再確定','SCR-002','OP-E-CONFIRM','action','別の再確認待ち状態は作らない。'),('i','未払いを再計算・照合','FUT-JLINK','OP-PAY-CALCULATE','end','支払済み結果は触らず差額案件へ。計算画面配置は提案。')],
[('a','b','判断'),('b','c','実際の変更'),('b','d','誤登録'),('c','e','登録'),('d','e','訂正'),('e','f','提出'),('f','g','不足あり'),('g','d','訂正して再提出'),('f','h','確認できた'),('h','i','未払いに影響')])
wf('WF-06','F 通勤届の提出・差戻し・認定','局担当者・給与班','局担当の通勤届入力','認定済み情報を計算が直接参照',CONFIRMED,['SCR-002'],['F-01','F-02','F-03','F-04','PAYREQ-05','FUT-STATE-F'],['SRC-F','SRC-PAY','SRC-SCREEN'],[
('a','局担当が自局の通勤届入力','SCR-002','OP-F-EDIT','start','通常非常勤職員。調査員は対象外。本人利用は将来。'),('b','経路・期間・入力を検証','SCR-002','','decision','経路別定期／ICが混在可。詳細検証条件は未決。'),('c','通勤タブで提出','SCR-002','OP-F-SUBMIT','action','給与班へ提出状態。'),('d','給与班が審査','SCR-002','','decision','認定に必要な内容を確認。'),('e','差戻し・外部で理由連絡','SCR-002','OP-F-RETURN','action','原則提出者が直し、同タブで再提出。'),('f','給与班が認定','SCR-002','OP-F-CERTIFY','action','認定時の自動PDF生成なし。'),('g','認定情報を直接参照','SCR-002','','end','別給与情報へ認定額を重複転記しない。')],
[('a','b','入力後'),('b','a','不備あり'),('b','c','検証可'),('c','d','審査'),('d','e','不備あり'),('e','a','修正・再提出'),('d','f','認定可'),('f','g','給与計算へ')])
wf('WF-07','F 変更認定・不支給・期間終了','局担当者・給与班','通勤認定後の事情変更','新認定、一時不支給または期間終了',CONFIRMED,['SCR-002','SCR-007'],['F-07','F-08','PAYREQ-05','FUT-STATE-F'],['SRC-F','SRC-PAY','SRC-OPEN'],[
('a','認定後に事情が変わる','SCR-002','','start','旧認定は保持。'),('b','変更の種類を確認','SCR-002','','decision','通勤変更／病気欠勤／受給要件喪失を分ける。'),('c','変更通勤届を新たに提出','SCR-002','OP-F-CHANGE','action','同じ通勤タブで新届出。'),('d','給与班が新認定','SCR-002','OP-F-CERTIFY','action','旧認定と精算・追給・返納を関連付け。'),('e','必要な精算・差額を確認','SCR-007','OP-RETRO-CALCULATE','end','具体精算式・支給月対応は未決。'),('f','該当期間を一時不支給','SCR-002','OP-F-NOPAY','end','病気・欠勤の不支給。認定期間終了とは異なる。'),('g','局担当が喪失を届出','SCR-002','','action','受給要件を失った届出。'),('h','給与班が期間終了を確定','SCR-002','OP-F-END','end','新たな認定終了状態は作らず終了日で管理。')],
[('a','b','確認'),('b','c','通勤内容変更'),('c','d','再審査・再認定'),('d','e','精算影響あり'),('b','f','病気・欠勤'),('b','g','要件喪失'),('g','h','確認後')])
wf('WF-08','F 通勤認定簿・別タブPDF','給与班・局担当者','通勤タブで認定を選択','A4横2ページを1PDFとして保存',CURRENT,['SCR-002','EXT-COMMUTE'],['SCR002-COM-003','FR-F-04','F-05'],['SRC-COMMUTE','SRC-STATUS','SRC-OPEN'],[
('a','職員・通勤認定を選択','SCR-002','OP-002-HISTORY','start','現行通常入口は認定簿表示だけ。'),('b','親職員・認定・権限確認','SCR-002','','decision','ボタン活性だけで認可を代替しない。'),('c','別タブHTMLを開く','SCR-002','OP-F-HTML','action','認定GUIDでHTML側が再取得。'),('d','表示取得は正常か','EXT-COMMUTE','','decision','削除・不一致・権限拒否では本文なし。'),('e','理由を表示・選択へ戻る','EXT-COMMUTE','OP-F-RETURN-HTML','action','旧職員や別認定の本文を残さない。'),('f','印刷・PDFを保存','EXT-COMMUTE','OP-F-PDF','action','A4横2ページ。超過は印刷停止。'),('g','元の通勤タブへ戻る','EXT-COMMUTE','OP-F-RETURN-HTML','end','印刷取消でも認定データは変更しない。')],
[('a','b','選択'),('b','c','整合あり'),('b','a','不一致'),('c','d','再取得'),('d','e','失敗・権限拒否'),('e','a','再選択'),('d','f','正常'),('f','g','保存／印刷取消')])
wf('WF-09','G 外部機関の決定結果登録','担当局・給与班・外部機関','外部で手続きし決定結果を受領','確定した決定結果を管理・計算へ利用',CONFIRMED,['SCR-002'],['G-01','G-02','G-04','G-05','G-06','SCR002-G-001','SCR002-G-002'],['SRC-G','SRC-SCREEN','SRC-PAY'],[
('a','外部機関で手続きを実施','','','start','電子申請・紙手続きはアプリ外。申請進捗をアプリ管理しない。'),('b','外部の決定結果を受領','','','external','紙・電子どちらも同じ登録扱い。'),('c','担当者が該当タブへ登録','SCR-002','OP-G-REGISTER','action','保険・共済・ハローワークは社会保険、住民税は税固定控除。'),('d','対象・登録内容を確認','SCR-002','','decision','外部決定内容を正とする。採否の再判断ではない。'),('e','誤入力・不足を修正','SCR-002','OP-E-CORRECT','action','元の決定を変更せず登録内容を整える。詳細手順は提案。'),('f','給与班が確認・確定','SCR-002','OP-G-CONFIRM','action','確定前は給与へ影響する内容を使用しない。'),('g','給与計算に影響するか','SCR-002','','decision','適用時点・個別項目は未入力。'),('h','確定結果を給与へ利用','SCR-002','','end','保険は登録額を使用。制度判定自動化なし。'),('i','決定結果として保持','SCR-002','','end','証憑方式・二重申請防止は未決。')],
[('a','b','決定'),('b','c','手動登録'),('c','d','確認待ち'),('d','e','入力不備'),('e','c','訂正'),('d','f','確認可'),('f','g','影響確認'),('g','h','影響あり'),('g','i','影響なし')])
wf('WF-10','勤務時間報告・取込とロック','局担当者・給与班','所属×勤務月の入力中報告','報告済み、または不完全隔離から復旧',CONFIRMED,['SCR-003','SCR-006'],['PAYREQ-06','PAYREQ-07'],['SRC-PAY','SRC-ATT','SRC-OPEN'],[
('a','有効な所属・勤務月を選択','SCR-003','OP-003-SELECT','start','現行全置換と異なる、10月7日改修先の取込図。'),('b','入力かExcel取込か','SCR-003','','decision','入力中だけ。報告済みは編集・取込不可。'),('c','日数・時間・備考を編集','SCR-003','OP-003-EDIT','action','改修先は職員行追加／削除可。超勤3桁・欠勤整数。'),('d','全件検証・処理中ロック','SCR-003','OP-003-IMPORT','action','同報告の編集・提出を停止し全行を検証。'),('e','掲載職員行を追加更新','SCR-003','OP-003-IMPORT','action','手修正上書き・空欄消去・0保持・未掲載保持。'),('f','反映は全て完了したか','SCR-003','','decision','全件事前検証でも反映途中障害はあり得る。'),('g','不完全として計算除外','SCR-003','OP-003-RECOVER','action','復旧方式PD-05。無条件ロールバック保証なし。'),('h','保存して読取りへ','SCR-003','OP-003-SAVE','action','保存失敗は入力保持。未保存の読取り切替は破棄確認。'),('i','勤務時間を報告','SCR-003','OP-003-REPORT','action','保存済み内容を報告。'),('j','報告済み・編集取込不可','SCR-003','','decision','給与班確認で訂正が必要なら差戻し。'),('k','給与班が差し戻す','SCR-003','OP-003-RETURN','action','訂正・再提出後、未払いの影響分は再計算・再照合。'),('l','給与計算で職員別に集計','SCR-003','','end','所属別報告から職員別集計。取込不完全は含めない。')],
[('a','b','入力中'),('b','c','画面入力'),('b','d','Excel'),('d','b','検証NG・修正'),('d','e','全件検証OK'),('e','f','結果確認'),('f','g','途中失敗'),('g','d','復旧・再実行'),('f','h','完了'),('c','h','保存'),('h','c','保存失敗・保持'),('h','i','確認後'),('i','j','報告済み'),('j','k','訂正必要'),('k','b','入力中へ'),('j','l','利用可能')])
wf('WF-11','期末・勤勉率の登録','会計課給与班（配置案）','職員と支給対象期間を選択','別々の率を計算根拠へ',CONFIRMED,['SCR-001','SCR-004','FUT-JLINK'],['PAYREQ-07'],['SRC-PAY','SRC-SCREEN','SRC-OPEN'],[
('a','期末勤勉画面を開く','SCR-001','OP-001-RATES','start','画面・入口は現行。以下の別率業務は改修先。'),('b','職員・対象期間を選択','SCR-004','','action','職員×支給対象期間。'),('c','期末率・勤勉率を別登録','SCR-004','OP-004-RATES','action','単一率へ統合しない。詳細項目・率範囲未入力。'),('d','必要条件を確認できるか','SCR-004','','decision','基礎額・式・端数・適用判定は未決。'),('e','未決条件を確認する','SCR-004','','end','未確認式を推測して本番計算しない。'),('f','計算版の根拠へ保持','FUT-JLINK','OP-PAY-CALCULATE','end','計算配置は提案。支払処理区分20等の割当ては未入力。')],
[('a','b','表示'),('b','c','登録'),('c','d','検証'),('d','c','入力不備'),('d','e','式等未確定'),('d','f','確定済条件のみ')])
wf('WF-12','給与計算から確定・支払記録','会計課給与班','確認済み元データと支給回','最新差分ゼロ確定・支払い済み記録',CONFIRMED,['SCR-002','SCR-003','SCR-004','FUT-JLINK','EXT-JINKYU','SCR-007'],['PAYREQ-07','PAYREQ-08','PAYREQ-10','I5','I7','I12'],['SRC-PAY','SRC-CALC','SRC-IF','SRC-JDETAIL'],[
('a','元データ確認・支給回選択','FUT-JLINK','OP-PAY-PERIOD','start','対象期間と支給日を区別。計算起動の配置は提案。'),('b','給与を計算・根拠保存','FUT-JLINK','OP-PAY-CALCULATE','action','確認済み条件・勤怠・認定通勤・登録控除・別率。'),('c','対象・A/M確認しExcel出力','FUT-JLINK','OP-JLINK-EXPORT','action','237列xlsx。出力前確認を行う。'),('d','人給取込・給与簿CSV出力','EXT-JINKYU','OP-JINKYU-PROCESS','external','外部操作。成功状態の手入力は設けない。'),('e','給与簿CSVを取込','FUT-JLINK','OP-JLINK-IMPORT','action','給与簿は読取り専用。失敗時は前回成功分を維持。'),('f','最新版のアプリ値と照合','FUT-JLINK','OP-JLINK-RECONCILE','action','出力後変更通知。古い版は一致基準にしない。'),('g','全体最新ゼロ・未解決なし','FUT-JLINK','','decision','未知・欠落・余分・重複を確認。表示絞込みで範囲を縮めない。'),('h','原因に応じ元データ訂正','SCR-002','OP-JLINK-CORRECT','action','再確認／再提出後に再計算。人給原因は外部で訂正。'),('i','ボタンで給与班確定','FUT-JLINK','OP-JLINK-CONFIRM','action','確認ダイアログなし。ゼロだけで自動確定しない。'),('j','外部で支払いを実施','','','external','アプリが実送金する要件はない。'),('k','支払い済みを記録','FUT-JLINK','OP-PAY-PAID','action','記録UI配置は提案。元の支払済み結果は不訂正。'),('l','最終根拠・照合履歴を保持','FUT-JLINK','OP-JLINK-HISTORY','end','中間版削除後も双方額・差額等を参照可能。保存条件PD-06。')],
[('a','b','確認済み'),('b','c','計算済み'),('c','d','外部へ'),('d','e','給与簿戻り'),('e','f','取込成功'),('e','e','失敗・前回保持で再取込'),('f','g','照合完了'),('g','h','差分／未解決'),('h','b','元データ修正後'),('h','d','人給側の訂正'),('g','f','結果更新・旧ゼロ失効'),('g','i','最新ゼロ'),('i','j','確定後'),('j','k','実施確認'),('k','l','記録後')])
wf('WF-13','人給出力・照合・差分再出力','会計課給与班','人給連携の支給回選択','差分訂正ループまたは支給回確定',CONFIRMED,['FUT-JLINK','EXT-JINKYU','SCR-002','SCR-003'],['JLINK-UI-01','JLINK-UI-03','JLINK-UI-04','JLINK-UI-05','JLINK-UI-06','JLINK-UI-07','JLINK-UI-08','JLINK-UI-09','JLINK-UI-10','JLINK-UI-11','I1','I2','I3','I4','I5','I6','I7','I8','I9','I10','I11','I12'],['SRC-JSCREEN','SRC-I','SRC-JDETAIL','SRC-TEST'],[
('a','支給回を3タブで保持','FUT-JLINK','OP-JLINK-SELECT','start','支給回の状況／出力／取込・照合。計算版選択なし。'),('b','初回は全職員を選択','FUT-JLINK','OP-JLINK-TARGET','action','職員絞込み・対象変更可能。'),('c','A/Mを一括・明細指定','FUT-JLINK','OP-JLINK-AM','action','職員判断。再出力でも自動Mにしない。'),('d','人数・明細数等を出力前確認','FUT-JLINK','OP-JLINK-EXPORT','decision','支給回・人数・明細数・A/M件数。'),('e','Excelを人給へ渡す','EXT-JINKYU','OP-JINKYU-PROCESS','external','人給取込エラーはI8。取得方式未決。'),('f','給与簿取込・最新版照合','FUT-JLINK','OP-JLINK-RECONCILE','action','最新版変更で「出力後に計算結果が変更されています」。'),('g','差分のみ・全件を切替','FUT-JLINK','OP-JLINK-FILTER','action','職員・期間・項目・アプリ値・給与簿値・差額。'),('h','差分・未解決が残るか','FUT-JLINK','','decision','全体最新ゼロを確認。外部成功証明ではない。'),('i','原因画面で訂正','SCR-002','OP-JLINK-CORRECT','action','勤怠はSCR-003。戻る際に支給回・職員を保持。'),('j','差分対応の明細を選択','FUT-JLINK','OP-JLINK-REEXPORT','action','差分項目行ではなく対応出力明細。変更可能・重複出力なし。'),('k','給与班が全体を確定','FUT-JLINK','OP-JLINK-CONFIRM','end','確認ダイアログなし。表示対象だけで判定しない。')],
[('a','b','初回出力'),('b','c','対象確認'),('c','d','出力準備'),('d','b','取消・対象を見直す'),('d','e','確認して出力'),('e','f','給与簿CSV戻り'),('f','g','結果表示'),('g','h','全体判定'),('h','i','差分あり'),('i','j','再計算後に再出力必要'),('i','f','再照合のみ必要'),('j','c','A/Mを職員判断'),('h','f','計算変更・旧ゼロ失効'),('h','k','全体最新ゼロ')])
wf('WF-14','遡及差額・追給・分割返納','給与班・業務マスタ管理者','過去支払い後の誤り・遡及改定','別追給または回収実績・残額管理',CONFIRMED,['SCR-006','SCR-007','FUT-JLINK'],['PAY-02','PAY-03','PAY-04','PAY-05','PAYREQ-08','PERIOD-04','PERIOD-05','SCR007-DIFF-001'],['SRC-AUTH','SRC-PAY','SRC-IF','SRC-OPEN'],[
('a','過去月の訂正・遡及改定','SCR-007','','start','元の支払済み結果を上書きしない。'),('b','旧結果と再計算との差額','SCR-007','OP-RETRO-CALCULATE','action','月別・項目別内訳を保持。式・端数は未決。'),('c','給与班が差額内訳を確認','SCR-007','','decision','確認待ち→確定。'),('d','元データ・条件を見直す','SCR-007','','action','未確定差額を支給・返納へ流さない。'),('e','差額を確定','SCR-007','OP-RETRO-CONFIRM','action','実施結果は差額状態と別記録。'),('f','追給か返納か','SCR-007','','decision','制度判定・例外詳細は未決。'),('g','過去月内訳を集約し出力へ','SCR-007','OP-RETRO-EXPORT','end','集約と対象日の両立は未決。月別との対応保持。'),('h','給与相殺・告知書を判断','SCR-007','OP-REPAY-METHOD','action','分割・両方法併用を許容。画面配置は提案。'),('i','回収実績・残額を記録','SCR-007','OP-REPAY-RECORD','action','案件に複数回収を関連。元支払を不訂正。'),('j','未回収残額があるか','SCR-007','','decision','過回収・取消・完了条件・相殺限度はPD-07。'),('k','実績と最終根拠を保持','SCR-007','','end','回収完了の正式判定条件は未決。')],
[('a','b','影響計算'),('b','c','確認待ち'),('c','d','要修正'),('d','b','再計算'),('c','e','確認できた'),('e','f','実施方法へ'),('f','g','追給'),('f','h','返納'),('h','i','回収実施後'),('i','j','残額確認'),('j','h','残額あり・次回収'),('j','k','記録整理')])
wf('WF-15','業務マスタ・権限と有効期間','業務マスタ管理者','管理権限と改定対象を確認','旧版保持・新期間適用・必要なら差額へ',CONFIRMED,['SCR-001','SCR-006','SCR-007'],['PAYREQ-09','AUTH-04','PAY-01','PAY-02','SCR006-RULE-001'],['SRC-AUTH','SRC-PAY','SRC-SCREEN','SRC-OPEN'],[
('a','メンテナンスを開く','SCR-001','OP-001-MAINTENANCE','start','現行入口は管理者限定。改修先の業務権限は別途判定。'),('b','業務マスタ管理権限ありか','SCR-006','','decision','給与班と兼務可能。システム管理者権限は別。'),('c','権限外は変更不可','SCR-006','','end','UIの切替値だけで許可しない。実効方式PD-04。'),('d','適用開始日付きで改定','SCR-006','OP-006-RULE','action','単価・区分・予算等。旧版と適用済み額を保持。'),('e','対象期間に新ルール適用','SCR-006','','decision','調査員初任給は採用日版。在職者も対象期間以降。'),('f','過去への影響は差額処理','SCR-007','OP-RETRO-CALCULATE','end','旧結果を不訂正。式・適用境界は未決。'),('g','使用停止・終了で履歴保持','SCR-006','OP-006-END','end','物理削除条件は未入力。'),('h','新期間への適用を確認','SCR-006','','end','PAY-02／AD-10。適用開始日以降の対象期間に新ルールを使用し、旧版・適用済み額を保持する。遡及影響や停止終了を全改定の必須工程としない。')],
[('a','b','入口と実効権限確認'),('b','c','権限なし'),('b','d','権限あり'),('d','e','改定保存'),('e','f','既計算期間に影響'),('e','g','停止・終了が必要'),('d','d','検証エラー・修正'),('e','h','将来期間の適用確認')])
# Keep the exact approved D decision boundary alongside the output operation.
next(o for o in ops if o['id']=='OP-JLINK-EXPORT')['notes'].extend([
'D1：実績U6は10、D2：本俸差額U6は11、D3：実績差額U6は11。D4：本俸E6は1か月前。',
'D5：本俸AZ6、D6：本俸CP6は決定額－差額。減算理由は今回支給対象月の欠勤。符号・二重減額・期待結果の試験は未実施。',
'D7：本俸差額E6、D8：実績差額E6は差額発生対象期間の日付。集約との具体的両立は未入力。',
'D9本俸差額AZ6、D10本俸差額CP6、D11本俸差額CI6、D12本俸差額CK6は保留・未回答。残る式をセル側優先と一括確定しない。',
'期末勤勉20・法改正30／31はコード意味のみ確認済み。明細割当ては未入力。'
])
# JSON field name 'from' is intentionally canonical despite Python keyword.
for w in workflows:
    for e in w['edges']: e['from']=e.pop('from_')
# Review-level scope caveats are placed on relevant screen cards and operations.
screens[3]['notes'].append('年末調整、法定控除の随時改定・定時決定は業務要件未確定。住民税年度更新手順も未入力。実行可能な業務フローは創作しない。')
screens[5]['notes'].append('勤務報告対象月を無効化しても保存済み報告を削除する要件はない。')
from payroll_flow_diagrams import apply_display_metadata
apply_display_metadata(workflows)

model=dict(metadata=dict(version='0.2-review',source_sha='b5e5d460fe19169252de05bb02bafc9461120540',original_main='252abe4aa5d3b1d99a584a30c97d9b48153c91f5',updated='2026-10-10',status='提案・レビュー用（未承認）'),sources=S,screens=screens,operations=ops,workflows=workflows)
def validate():
    ids=lambda seq:{r['id'] for r in seq}
    sid,oid,srcid=ids(screens),ids(ops),ids(S)
    assert len(sid)==len(screens) and len(oid)==len(ops)
    assert len({o['transition_id'] for o in ops})==len(ops)
    allowed={CURRENT,CONFIRMED,PROPOSED,UNDECIDED}
    for item in S: assert (ROOT/item['path']).is_file(),item['path']
    for s in screens:
        assert s['status'] in allowed and set(s['source_ids'])<=srcid
    fields={'id','transition_id','screen_id','destination_screen_id','title','business_id','status','requirements','source_ids','origin_tab','origin_mode','destination_tab','destination_mode','control','method','roles','row_scope','visible','enabled','preconditions','validation','process','reads','writes','retained','reset','success','failure','cancel','unsaved','acceptance','notes'}
    arrays={'requirements','source_ids','roles','reads','writes','acceptance','notes'}
    for o in ops:
        assert set(o)==fields, (o['id'],set(o)^fields)
        assert o['screen_id'] in sid and o['destination_screen_id'] in sid
        assert o['status'] in allowed and set(o['source_ids'])<=srcid
        for k,v in o.items(): assert isinstance(v,list if k in arrays else str),(o['id'],k,type(v))
        assert len(o['title'])<=22,(o['id'],o['title'])
    for w in workflows:
        assert set(w['source_ids'])<=srcid and set(w['screen_ids'])<=sid
        stepids=ids(w['steps']); assert len(stepids)==len(w['steps'])
        assert any(s['kind']=='start' for s in w['steps']) and any(s['kind']=='end' for s in w['steps'])
        for s in w['steps']:
            assert s['screen_id'] in sid or s['screen_id']==''
            assert s['operation_id'] in oid or s['operation_id']==''
            assert s['kind'] in {'start','action','decision','external','end'}
            assert len(s['label'])<=22,(w['id'],s['label'])
        for e in w['edges']:
            assert e['from'] in stepids and e['to'] in stepids
            assert len(e['label'])<=22
    assert [s['tabs'] for s in screens if s['id']=='SCR-002'][0]==['基本情報','勤務条件','通勤','社会保険','税固定控除','給与簿']
    assert [s['tabs'] for s in screens if s['id']=='FUT-JLINK'][0]==['支給回の状況','出力','取込・照合']
    assert not any(o['screen_id']=='SCR-001' and o['destination_screen_id']=='SCR-005' for o in ops)
    assert {f'I{i}' for i in range(1,13)} <= set(sum([o['requirements'] for o in ops],[]))
if __name__=='__main__':
    validate()
    out=ROOT/'docs/review/pay-html-001/data/model.json'
    out.parent.mkdir(parents=True,exist_ok=True)
    out.write_text(json.dumps(model,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
    print(json.dumps(dict(path=str(out),screens=len(screens),operations=len(ops),workflows=len(workflows),sources=len(S),bytes=out.stat().st_size),ensure_ascii=False))
