Set(varFetched111,Blank()); Set(varFetchError111,Blank()); Set(varHistoryId111,Blank()); Set(varPayrollCellTitle111,Blank());Set(varPayrollCellText111,Blank()); Set(varHistoryStaff111,StaffSelected.StaffId);
Clear(colCommute111);Clear(colWork111);Clear(colSocial111);Clear(colTax111);Clear(colResident111);Clear(colHistory111);Clear(colPayrollSource111);Clear(colPayrollColumns111);Clear(colPayrollExceptions111);
Set(varStaffSource111,LookUp(colStaffSource111,職員番号=StaffSelected.StaffId));
If(!IsBlank(StaffSelected.StaffId),IfError(
 ClearCollect(colCommute111,Filter('T_通勤_STUDIO',職員基本.職員番号=StaffSelected.StaffId));
 ClearCollect(colWork111,If(UiFixtureCount>=0,Filter(StaffWorkHistory,StaffId=StaffSelected.StaffId),ForAll(Filter('T_給与勤務条件_STUDIO',職員基本.職員番号=StaffSelected.StaffId) As p,{StaffId:p.職員番号,RecordId:Text(p.crb3c_studioworkconditionid),Start:p.適用開始日,End:p.適用終了日,F_staffnumber:p.'職員番号',F_fullname:p.'氏名',F_startdate:p.'適用開始日',F_enddate:p.'適用終了日',F_transferkind:p.'異動区分',F_appointmentreason:p.'発令事由区分',F_dailyrate:p.'日額単価',F_workstart:p.'勤務時間開始',F_workend:p.'勤務時間終了',F_dailyhours:p.'１日あたりの勤務時間',F_overtimebaserate:p.'超勤基礎単価（参考）',F_budgetitem:p.'支出科目名',F_appointmentdraft:p.'辞令案',F_appointmentcomment:p.'辞令コメント',F_notes:p.'その他備考'})));
 ClearCollect(colSocial111,If(UiFixtureCount>=0,Filter(StaffSocialHistory,StaffId=StaffSelected.StaffId),ForAll(Filter('T_社会保険_STUDIO',職員基本.職員番号=StaffSelected.StaffId) As p,{StaffId:p.職員番号,RecordId:Text(p.crb3c_studiosocialinsuranceid),Category:p.職員雇用区分,F_staffnumber:p.'職員番号',F_fullname:p.'氏名',F_employmentcategory:p.'職員雇用区分',F_birthdate:p.'生年月日',F_ageapril:p.'4/1時点年齢',F_agemarch:p.'3/1時点年齢',F_carestatus:p.'介護徴収該当',F_pensionexemption:p.'厚生年金免除該当',F_elderstatus:p.'後期高齢者徴収該当',F_pensionstart:p.'厚生徴収開始月',F_pensionend:p.'厚生徴収終了月日',F_pensiongrade:p.'厚生_級',F_pensionmonthly:p.'厚生月額',F_multiemployer:p.'二以上_該当',F_multiemployerpensionamount:p.'二以上_通知額_厚生年金保険',F_corporatepension:p.'企業年金_該当',F_corporatepensionamount:p.'企業年金通知額',F_shortstart:p.'短期徴収開始月日',F_shortend:p.'短期徴収終了月日',F_longstart:p.'長期徴収開始月',F_longend:p.'長期徴収終了月日',F_graderevision:p.'等級改定日',F_shortgrade:p.'短期_級',F_shortmonthly:p.'短期月額',F_longgrade:p.'長期_級',F_longmonthly:p.'長期月額'})));
 ClearCollect(colTax111,If(UiFixtureCount>=0,Filter(StaffTaxHistory,StaffId=StaffSelected.StaffId),ForAll(Filter('T_税・固定控除_STUDIO',職員基本.職員番号=StaffSelected.StaffId) As p,{StaffId:p.職員番号,RecordId:Text(p.crb3c_studiotaxfixeddeductionid),Start:p.適用開始日,End:p.適用終了日,F_staffnumber:p.'職員番号',F_fullname:p.'氏名',F_startdate:p.'適用開始日',F_enddate:p.'適用終了日',F_taxtable:p.'税表区分',F_dependents:p.'扶養控除対象人数',F_employmentinsurance:p.'雇用保険加入区分',F_savingsmonthly:p.'共済貯金月額',F_loanmonthly:p.'共済貸付月額'})));
 ClearCollect(colResident111,ForAll(Filter('T_住民税_STUDIO',職員基本.職員番号=StaffSelected.StaffId) As p,{StaffId:p.職員番号,RecordId:"R:" & Text(p.crb3c_studioresidenttaxid),Period:p.期間区分,F_staffnumber:p.'職員番号',F_fullname:p.'氏名',F_periodcategory:p.'期間区分',F_monthlyamount:p.'住民税月額',F_municipalitycode:p.'自治体コード',F_municipalityname:p.'納付先自治体'}));
 ClearCollect(colPayrollSource111,Filter('T_基準給与簿_STUDIO',crb3c_staffnumber=StaffSelected.StaffId));
 If(CountRows(colCommute111)>=500 || CountRows(colPayrollSource111)>=500 || CountRows(colWork111)>=500 || CountRows(colSocial111)>=500 || CountRows(colTax111)>=500 || CountRows(colResident111)>=500,Error({Kind:ErrorKind.Validation,Message:"詳細の取得上限に達しました"}));
 ClearCollect(colHistory111,
 ForAll(colWork111 As p,{Section:"Work",RecordId:p.RecordId,Title:p.RecordId,Period:Text(p.Start,"yyyy/mm/dd") & " ～ " & If(p.End=Date(2099,3,31),"",Text(p.End,"yyyy/mm/dd")),State:If(p.Start>Today(),"予定",p.End<Today(),"過去","現行")}),
 ForAll(colSocial111 As p,{Section:"Social",RecordId:p.RecordId,Title:p.RecordId,Period:p.Category,State:"登録済"}),
 ForAll(colResident111 As p,{Section:"Tax",RecordId:p.RecordId,Title:"住民税 / " & Coalesce(p.Period,""),Period:Coalesce(p.Period,""),State:"登録済"}),
 ForAll(colTax111 As p,{Section:"Tax",RecordId:p.RecordId,Title:p.RecordId,Period:Text(p.Start,"yyyy/mm/dd") & " ～ " & If(p.End=Date(2099,3,31),"",Text(p.End,"yyyy/mm/dd")),State:If(p.Start>Today(),"予定",p.End<Today(),"過去","現行")}),
 ForAll(colCommute111 As p,{Section:"Commute",RecordId:Text(p.T_通勤_STUDIO),Title:p.通勤認定ID & " / " & p.支給方式,Period:Text(p.適用開始日,"yyyy/mm/dd") & " ～ " & Text(p.適用終了日,"yyyy/mm/dd"),State:If(p.適用開始日>Today(),"予定",!IsBlank(p.適用終了日)&&p.適用終了日<Today(),"過去","現行")}));
Set(varHistoryId111,First(Filter(colHistory111,Section=varStaffDetailTab111)).RecordId);Clear(colPayrollColumns111); Clear(colPayrollExceptions111);
ForAll(colPayrollSource111 As p,With({dt:IfError(With({m:Match(Trim(Coalesce(p.crb3c_payment_date,"")),"(?<Era>令和|平成|昭和|R|H|S)(?<EraYear>元|[0-9]{1,2})[年./-](?<M>[0-9]{1,2})[月./-](?<D>[0-9]{1,2})日?",MatchOptions.Complete)},
 If(IsBlank(m.FullMatch),Blank(),With({y:Switch(m.Era,"令和",2018,"R",2018,"平成",1988,"H",1988,"昭和",1925,"S",1925)+If(m.EraYear="元",1,Value(m.EraYear)),mo:Value(m.M),dy:Value(m.D)},
 With({dt:Date(y,mo,dy)},If(Year(dt)=y && Month(dt)=mo && Day(dt)=dy && Value(Substitute(m.EraYear,"元","1"))>0 && Switch(m.Era,"令和",dt>=Date(2019,5,1),"R",dt>=Date(2019,5,1),"平成",dt>=Date(1989,1,8)&&dt<Date(2019,5,1),"H",dt>=Date(1989,1,8)&&dt<Date(2019,5,1),"昭和",dt>=Date(1926,12,25)&&dt<Date(1989,1,8),"S",dt>=Date(1926,12,25)&&dt<Date(1989,1,8),false),dt,Blank()))))),Blank())},
 If(IsBlank(dt),Collect(colPayrollExceptions111,{RecordId:Text(p.crb3c_studiopayrollledgerid),PaymentText:p.crb3c_payment_date}),
 dt>=varPayrollStart111 && dt<DateAdd(varPayrollEnd111,1,TimeUnit.Months),
 Collect(colPayrollColumns111,{RecordId:Text(p.crb3c_studiopayrollledgerid),PaymentDate:dt,Sequence:p.crb3c_sequence,Record:p}))));
 Set(varFetched111,Now()),
 Clear(colCommute111);Clear(colWork111);Clear(colSocial111);Clear(colTax111);Clear(colResident111);Clear(colHistory111);Clear(colPayrollSource111);Clear(colPayrollColumns111);Clear(colPayrollExceptions111);Set(varHistoryId111,Blank());Set(varFetchError111,"詳細データを取得できませんでした：" & FirstError.Message);Notify(varFetchError111,NotificationType.Error)),Set(varFetched111,Now()));
